@echo off
FOR %%A IN (
	"E:\MyWork2\Proj-supergenius-XO\Admin"
	"E:\MyWork2\Proj-supergenius-XO\Finance"
	"E:\MyWork2\Proj-supergenius-XO\Official"
	"E:\MyWork2\Proj-supergenius-XO\Common"
	"E:\MyWork2\Proj-supergenius-XO\User"
	"E:\MyWork2\Proj-supergenius-XO\Tpi"
	"E:\MyWork2\Proj-supergenius-XO\Moral"
	"E:\MyWork2\Proj-supergenius-XO\Manager"
	"E:\MyWork2\Proj-supergenius-XO\Account"
        "E:\MyWork2\Proj-supergenius-XO\Enterpriser"
	"E:\MyWork2\Proj-supergenius-XO\Wechat"
	"E:\MyWork2\Proj-supergenius-server\Admin"
	"E:\MyWork2\Proj-supergenius-server\Finance"
	"E:\MyWork2\Proj-supergenius-server\Official"
	"E:\MyWork2\Proj-supergenius-server\Common"
	"E:\MyWork2\Proj-supergenius-server\User"
	"E:\MyWork2\Proj-supergenius-server\Tpi"
	"E:\MyWork2\Proj-supergenius-server\Moral"
	"E:\MyWork2\Proj-supergenius-server\Manager"
	"E:\MyWork2\Proj-supergenius-server\Account"
	"E:\MyWork2\Proj-supergenius-server\Enterpriser"
	"E:\MyWork2\Proj-supergenius-server\Wechat"
	"E:\MyWork2\Proj-supergenius-admin"
	"E:\MyWork2\Proj-supergenius-finance"
	"E:\MyWork2\Proj-supergenius-official"
	"E:\MyWork2\Proj-supergenius-user"
	"E:\MyWork2\Proj-supergenius-tpi"
	"E:\MyWork2\Proj-supergenius-moral"
	"E:\MyWork2\Proj-supergenius-account"
	"E:\MyWork2\Proj-supergenius-data"
	"E:\MyWork2\Proj-supergenius-manager"
        "E:\MyWork2\Proj-supergenius-enterpriser"
	"E:\MyWork2\Proj-supergenius-wechat"
) DO START TortoiseProc.exe /command:commit /path:%%A /closeonend:0