var objects = [
		 {name: '北京  BEIJING BJ', value: '北京'},
		 {name: '东城区  DONGCHENG  DCQ', value: '东城区'},
		 {name: '西城区  XICHENG  XCQ', value: '西城区'},
		 {name: '朝阳区  CHAOYANG  CYQ', value: '朝阳区'},
		 {name: '海淀区  HAIDIAN  HDN', value: '海淀区'},
		 {name: '石景山  SHIJINGSHAN  SJS', value: '石景山'},
		 {name: '门头沟  MENTOUGOU  MTG', value: '门头沟'},
		 {name: '丰台区  FENGTAI  FTQ', value: '丰台区'},
		 {name: '房山区  FANGSHAN  FSQ', value: '房山区'},
		 {name: '大兴区  DAXING  DXQ', value: '大兴区'},
		 {name: '通州区  TONGZHOU  TZQ', value: '通州区'},
		 {name: '顺义区  SHUNYI  SYI', value: '顺义区'},
		 {name: '平谷区  PINGGU  PGU', value: '平谷区'},
		 {name: '昌平区  CHANGPING  CPX', value: '昌平区'},
		 {name: '怀柔区  HUAIROU  HRX', value: '怀柔区'},
		 {name: '延庆县  YANQING  YQX', value: '延庆县'},
		 {name: '密云县  MIYUN  MYN', value: '密云县'},
		 {name: '上海  SHANGHAI  SH', value: '上海'},
		 {name: '浦东新区  PUDONGXINQU  PDX', value: '浦东新区'},
		 {name: '徐汇区  XUHUI  XHI', value: '徐汇区'},
		 {name: '长宁区  CHANGNING', value: '长宁区'},
		 {name: '普陀区  PUTUO  PTO', value: '普陀区'},
		 {name: '闸北区  ZHABEI  ZBE', value: '闸北区'},
		 {name: '虹口区  HONGKOU  HKQ', value: '虹口区'},
		 {name: '杨浦区  YANGPU  YPU', value: '杨浦区'},
		 {name: '黄浦区  HUANGPU  HGP', value: '黄浦区'},
		 {name: '静安区  JINGAN  JAQ', value: '静安区'},
		 {name: '宝山区  BAOSHAN  BAO', value: '宝山区'},
		 {name: '闵行区  MINHANG  MHQ', value: '闵行区'},
		 {name: '嘉定区  JIADING  JDG', value: '嘉定区'},
		 {name: '金山区  JINSHAN', value: '金山区'},
		 {name: '松江区  SONGJIANG  SOJ', value: '松江区'},
		 {name: '青浦区  QINGPU  QPU', value: '青浦区'},
		 {name: '奉贤区  FENGXIAN  FXI', value: '奉贤区'},
		 {name: '崇明县  CHONGMING  CMI', value: '崇明县'},
		 {name: '天津  TIANJIN  TJ', value: '天津'},
		 {name: '和平区  HEPING  HPQ', value: '和平区'},
		 {name: '河东区  HEDONG  HDL', value: '河东区'},
		 {name: '河西区  HEXI HXQ', value: '河西区'},
		 {name: '南开区  NANKAI NKQ', value: '南开区'},
		 {name: '河北区  HEBEI HBQ', value: '河北区'},
		 {name: '红桥区  HONGQIAO HQO', value: '红桥区'},
		 {name: '塘沽区  TANGKU TGA', value: '塘沽区'},
		 {name: '汉沽区  HANKU HGQ', value: '汉沽区'},
		 {name: '大港区  DAGANG DGJ', value: '大港区'},
		 {name: '东丽区  DONGLI DLI', value: '东丽区'},
		 {name: '西青区  XIQING XQG', value: '西青区'},
		 {name: '津南区  JINNAN JNQ', value: '津南区'},
		 {name: '北辰区  BEICHEN BCQ', value: '北辰区'},
		 {name: '武清区  WUQING WQX', value: '武清区'},
		 {name: '宝坻区  BAODI BDI', value: '宝坻区'},
		 {name: '宁河县  NINGHE NHE', value: '宁河县'},
		 {name: '静海县  JINGHAI JHT', value: '静海县'},
		 {name: '蓟  县  JIXIAN JXI', value: '蓟 县'},
		 {name: '开发区  JINGJIKAIFAQU KFQ', value: '开发区'},
		 {name: '滨海区  BINHAIXINQU BHI', value: '滨海区'},
		 {name: '重庆 CHONGQING CQ', value: '重庆'},
		 {name: '渝中区  YUZHONG YZQ', value: '渝中区'},
		 {name: '江北区  JIANGBEI JBE', value: '江北区'},
		 {name: '南岸区  NANAN NAQ', value: '南岸区'},
		 {name: '沙坪坝  SHAPINGVA SPB', value: '沙坪坝'},
		 {name: '九龙坡  JIULONGPO JLP', value: '九龙坡'},
		 {name: '大渡口  DADUKOU DDK', value: '大渡口'},
		 {name: '北碚区  BEIBEI BBE', value: '北碚区'},
		 {name: '巴南区  BANAN BNN', value: '巴南区'},
		 {name: '渝北区  YUBEI YBE', value: '渝北区'},
		 {name: '永川区  YONGCHUAN YCP', value: '永川区'},
		 {name: '涪陵区  FULING FLG', value: '涪陵区'},
		 {name: '合川区  HECHUAN HEC', value: '合川区'},
		 {name: '江津区  JIANGJIN JJY', value: '江津区'},
		 {name: '长寿区  CHANGSHOU CSO', value: '长寿区'},
		 {name: '南川区  NANCHUAN NCU', value: '南川区'},
		 {name: '万州区  WANZHOU WZO', value: '万州区'},
		 {name: '黔江区  QIANJIANG QJX', value: '黔江区'},
		 {name: '綦江区  QIJIANG QJG', value: '綦江区'},
		 {name: '潼南县  TONGNANXIAN TNN', value: '潼南县'},
		 {name: '铜梁区  TONGLIANG TGL', value: '铜梁区'},
		 {name: '大足区  DAZU DZX', value: '大足区'},
		 {name: '荣昌县  RONGCHANGXIAN RGC', value: '荣昌县'},
		 {name: '璧山区  BISHAN BSY', value: '璧山区'},
		 {name: '垫江县  DIANJIANGXIAN DJG', value: '垫江县'},
		 {name: '武隆县  WULONGXIAN WLG', value: '武隆县'},
		 {name: '丰都县  FENGDOUXIAN FDU', value: '丰都县'},
		 {name: '城口县  CHENGKOUXIAN CKO', value: '城口县'},
		 {name: '梁平县  LIANGPINGXIAN LGP', value: '梁平县'},
		 {name: '开县 KAIXIAN KAI', value: '开县'},
		 {name: '巫溪县 WUXIXIAN WXX', value: '巫溪县'},
		 {name: '巫山县 WUSHANXIAN WSN', value: '巫山县'},
		 {name: '奉节县 FENGJIEXIAN FJE', value: '奉节县'},
		 {name: '云阳县 YUNYANGXIAN YNY', value: '云阳县'},
		 {name: '忠县 ZHONGXIAN ZHX', value: '忠县'},
		 {name: '石柱 SHIZHU SZY', value: '石柱'},
		 {name: '彭水县  PENGSHUI PSU', value: '彭水县'},
		 {name: '酉阳县  YOUYANG YUY', value: '酉阳县'},
		 {name: '石柱县  SHIZHUTUJIAZUZIZHIXIAN SZY', value: '石柱县'},
		 {name: '秀山县  XIUSHAN XUS', value: '秀山县'},
		 {name: '广东省  GUANGDONG GD', value: '广东省'},
		 {name: '广州 GUANGZHOU CAN', value: '广州'},
		 {name: '白云区  BAIYUN', value: '白云区'},
		 {name: '天河区  TIANHE THQ', value: '天河区'},
		 {name: '越秀区  YUEXIU YXU', value: '越秀区'},
		 {name: '海珠区  ZHUHAI HZU', value: '海珠区'},
		 {name: '黄埔区  HUANGPU HPU', value: '黄埔区'},
		 {name: '荔湾区  LIWAN LWQ', value: '荔湾区'},
		 {name: '番禺区  FANYU PNY', value: '番禺区'},
		 {name: '花都区  HUADU HDU', value: '花都区'},
		 {name: '萝岗区  LUOGANG', value: '萝岗区'},
		 {name: '南沙区  NANSHA NSA', value: '南沙区'},
		 {name: '从化区  CONGHUA CNH', value: '从化区'},
		 {name: '增城区  ZENGCHENG ZEC', value: '增城区'},
		 {name: '潮州 CHAOZHOU CZY', value: '潮州'},
		 {name: '东莞 DONGGUAN DGG', value: '东莞'},
		 {name: '南城区  NANCHENGQU NCE', value: '南城区'},
		 {name: '东城区  DONGCHENGQU DCQ', value: '东城区'},
		 {name: '万江区  WANJIANGQU', value: '万江区'},
		 {name: '莞城区  WANCHENGQU', value: '莞城区'},
		 {name: '石龙镇  SHILONGZHEN SIL', value: '石龙镇'},
		 {name: '虎门镇  HUMENZHEN', value: '虎门镇'},
		 {name: '麻涌镇  MAYONGZHEN', value: '麻涌镇'},
		 {name: '道滘镇  DAOJIAOZHEN', value: '道滘镇'},
		 {name: '石碣镇  SHIJIEZHEN', value: '石碣镇'},
		 {name: '沙田镇  SHATIANZHEN', value: '沙田镇'},
		 {name: '望牛墩  WANGNIUDUNZHEN', value: '望牛墩'},
		 {name: '洪梅镇  HONGMEIZHEN', value: '洪梅镇'},
		 {name: '茶山镇  CHASHANZHEN', value: '茶山镇'},
		 {name: '寮步镇  LIAOBUZHEN', value: '寮步镇'},
		 {name: '大岭山  DALINGSHANZHEN', value: '大岭山'},
		 {name: '大朗镇  DALANGZHEN', value: '大朗镇'},
		 {name: '黄江镇  HUANGJIANGZHEN', value: '黄江镇'},
		 {name: '樟木头  ZHANGMUTOUZHEN', value: '樟木头'},
		 {name: '凤岗镇  FENGGANGZHEN', value: '凤岗镇'},
		 {name: '塘厦镇  TANGXIAZHEN', value: '塘厦镇'},
		 {name: '谢岗镇  XIEGANGZHEN', value: '谢岗镇'},
		 {name: '厚街镇  HOUJIEZHEN', value: '厚街镇'},
		 {name: '清溪镇  QINGXIZHEN', value: '清溪镇'},
		 {name: '常平镇  CHANGPINGZHEN', value: '常平镇'},
		 {name: '桥头镇  QIAOTOUZHEN', value: '桥头镇'},
		 {name: '横沥镇  HENGLIZHEN', value: '横沥镇'},
		 {name: '东坑镇  DONGKENGZHEN', value: '东坑镇'},
		 {name: '企石镇  QISHIZHEN', value: '企石镇'},
		 {name: '石排镇  SHIPAIZHEN', value: '石排镇'},
		 {name: '长安镇  CHANGANZHEN', value: '长安镇'},
		 {name: '中堂镇  ZHONGTANGZHEN', value: '中堂镇'},
		 {name: '高埗镇  GAOBUZHEN', value: '高埗镇'},
		 {name: '松山湖  SONGSHANHUGAOXINQU SSQ', value: '松山湖'},
		 {name: '佛山 FOSHAN FOS', value: '佛山'},
		 {name: '禅城区  CHANCHENGQU', value: '禅城区'},
		 {name: '南海区  NANHAIQU NAH', value: '南海区'},
		 {name: '顺德区  SHUNDEQU SUD', value: '顺德区'},
		 {name: '三水区  SANSHUIQU SJQ', value: '三水区'},
		 {name: '高明区  GAOMINGQU GOM', value: '高明区'},
		 {name: '新城区  DONGPINGXINCHENG', value: '新城区'},
		 {name: '大沥  DALI', value: '大沥'},
		 {name: '黄岐  HUANGQI', value: '黄岐'},
		 {name: '西樵  XIQIAO', value: '西樵'},
		 {name: '南庄  NANZHUANG', value: '南庄'},
		 {name: '惠州  HUIZHOU HUI', value: '惠州'},
		 {name: '清远  QINGYUAN QYN', value: '清远'},
		 {name: '汕头  SHANTOU SWA', value: '汕头'},
		 {name: '深圳  SHENZHEN SZX', value: '深圳'},
		 {name: '罗湖区  LUOHU LHQ', value: '罗湖区'},
		 {name: '福田区  FUTIAN FTN', value: '福田区'},
		 {name: '南山区  NANSHAN', value: '南山区'},
		 {name: '宝安区  ANBAO BAQ', value: '宝安区'},
		 {name: '龙岗区  LONGGANG LGG', value: '龙岗区'},
		 {name: '盐田区  YANTIAN YTQ', value: '盐田区'},
		 {name: '光明新区  GUANGMINGXINQU', value: '光明新区'},
		 {name: '坪山新区  PINGSHANXINQU', value: '坪山新区'},
		 {name: '大鹏新区  DAPENGXINQU', value: '大鹏新区'},
		 {name: '龙华新区  LONGHUAXINQU', value: '龙华新区'},
		 {name: '顺德  SHUNDE SUD', value: '顺德'},
		 {name: '湛江  ZHANJIANG ZHA', value: '湛江'},
		 {name: '肇庆  ZHAOQING ZQG', value: '肇庆'},
		 {name: '中山  ZHONGSHAN', value: '中山'},
		 {name: '珠海  ZHUHAI ZUH', value: '珠海'},
		 {name: '香洲区 XIANGZHOUQU XZQ', value: '香洲区'},
		 {name: '斗门区 DOUMENQU DOU', value: '斗门区'},
		 {name: '金湾区 JINWANQU', value: '金湾区'},
		 {name: '横琴新区 HENGQINXINQU', value: '横琴新区'},
		 {name: '江门 JIANGMEN JMN', value: '江门'},
		 {name: '阳江 YANGJIANG YJI', value: '阳江'},
		 {name: '韶关 SHAOGUAN HSC', value: '韶关'},
		 {name: '茂名 MAOMING MMI', value: '茂名'},
		 {name: '梅州 MEIZHOU MXZ', value: '梅州'},
		 {name: '汕尾 SHANWEI SWE', value: '汕尾'},
		 {name: '河源 HEYUAN HEY', value: '河源'},
		 {name: '揭阳 JIEYANG JIY', value: '揭阳'},
		 {name: '云浮 YUNFU YFS', value: '云浮'},
		 {name: '开平 KAIPING', value: '开平'},
		 {name: '台山 TAISHAN TSS', value: '台山'},
		 {name: '普宁 PUNING PNG', value: '普宁'},
		 {name: '南沙 NANSHA NSA', value: '南沙'},
		 {name: '龙川 LONGCHUAN LCY', value: '龙川'},
		 {name: '鹤山 HESHAN', value: '鹤山'},
		 {name: '江苏省 JIANGSU JS', value: '江苏省'},
		 {name: '南京 NANJING NKG', value: '南京'},
		 {name: '玄武区 XUANWU XWU', value: '玄武区'},
		 {name: '白下区 BAIXIA BXQ', value: '白下区'},
		 {name: '秦淮区 QINHUAI QHU', value: '秦淮区'},
		 {name: '建邺区 JIANYE JYQ', value: '建邺区'},
		 {name: '鼓楼区 GULOU GLK', value: '鼓楼区'},
		 {name: '下关区 XIAGUAN XGQ', value: '下关区'},
		 {name: '浦口区 PUKOU PKO', value: '浦口区'},
		 {name: '六合区 LIUHE LHE', value: '六合区'},
		 {name: '栖霞区 QIXIA', value: '栖霞区'},
		 {name: '雨花台 YUHUATAI', value: '雨花台'},
		 {name: '江宁区 JIANGNING JNX', value: '江宁区'},
		 {name: '溧水县 LISHUI LIS', value: '溧水县'},
		 {name: '高淳县 GAOCHUN GCN', value: '高淳县'},
		 {name: '大厂区 DACHANGQU', value: '大厂区'},
		 {name: '常熟 CHANGSHU CGS', value: '常熟'},
		 {name: '常州 CHANGZHOU CZX', value: '常州'},
		 {name: '天宁区 TIANNINGQU TNQ', value: '天宁区'},
		 {name: '钟楼区 ZHONGLOUQU ZLQ', value: '钟楼区'},
		 {name: '戚墅堰 QISHUYANQU QSY', value: '戚墅堰'},
		 {name: '郊区 JIAOQU JQC', value: '郊区'},
		 {name: '新北区 XINBEIQU', value: '新北区'},
		 {name: '武进区 WUJINQU WJN', value: '武进区'},
		 {name: '溧阳市 LIYANGSHI LYR', value: '溧阳市'},
		 {name: '金坛市 JINTANSHI JTS', value: '金坛市'},
		 {name: '昆山 KUNSHAN KUS', value: '昆山'},
		 {name: '连云港 LIANYUNGANG', value: '连云港'},
		 {name: '南通 NANTONG NTG', value: '南通'},
		 {name: '苏州 SUZHOU SZH', value: '苏州'},
		 {name: '金阊区 JINCHANG JCA', value: '金阊区'},
		 {name: '沧浪区 CANGLANG CLQ', value: '沧浪区'},
		 {name: '平江区 PINGJIANG', value: '平江区'},
		 {name: '工业园 GONGYEYUAN', value: '工业园'},
		 {name: '高新区 GAOXIN', value: '高新区'},
		 {name: '吴中区 WUZHONG', value: '吴中区'},
		 {name: '相城区 XIANGCHENG', value: '相城区'},
		 {name: '张家港 ZHANGJIAGANG ZJG', value: '张家港'},
		 {name: '常熟市 CHANGSHU CGS', value: '常熟市'},
		 {name: '太仓市 TAICANG TAC', value: '太仓市'},
		 {name: '昆山市 KUNSHAN KUS', value: '昆山市'},
		 {name: '吴江市 WUJIANG WUJ', value: '吴江市'},
		 {name: '虎丘区 HUQIUQU', value: '虎丘区'},
		 {name: '玉山镇 YUSHANZHEN YUS', value: '玉山镇'},
		 {name: '巴城镇 BACHENGZHEN', value: '巴城镇'},
		 {name: '周市镇 ZHOUSHIZHEN', value: '周市镇'},
		 {name: '陆家镇 LUJIAZHEN', value: '陆家镇'},
		 {name: '花桥镇 HUAQIAOZHEN', value: '花桥镇'},
		 {name: '淀山湖 DIANSHANHUZHEN', value: '淀山湖'},
		 {name: '张浦镇 ZHANGPUZHEN', value: '张浦镇'},
		 {name: '周庄镇 ZHOUZHUANGZHEN', value: '周庄镇'},
		 {name: '千灯镇 QIANDENGZHEN', value: '千灯镇'},
		 {name: '锦溪镇 JINXIZHEN', value: '锦溪镇'},
		 {name: '开发区 KAIFAQU', value: '开发区'},
		 {name: '太仓 TAICANG TAC', value: '太仓'},
		 {name: '无锡 WUXI WUX', value: '无锡'},
		 {name: '崇安区 CHONGANQU CGA', value: '崇安区'},
		 {name: '北塘区 BEITANGQU BTQ', value: '北塘区'},
		 {name: '南长区 NANCHANGQU NCG', value: '南长区'},
		 {name: '锡山区 XISHANQU XSS', value: '锡山区'},
		 {name: '惠山区 HUISHANQU', value: '惠山区'},
		 {name: '滨湖区 BINHUQU', value: '滨湖区'},
		 {name: '新区 XINQU XNQ', value: '新区'},
		 {name: '宜兴市 YIXINGSHI  YIX', value: '宜兴市'},
		 {name: '江阴市  JIANGYINSHI  JIA', value: '江阴市'},
		 {name: '徐州  XUZHOU  XUZ', value: '徐州'},
		 {name: '扬州  YANGZHOU  YZH', value: '扬州'},
		 {name: '镇江  ZHENJIANG  ZHE', value: '镇江'},
		 {name: '淮安  HUAIAN  HAS', value: '淮安'},
		 {name: '盐城  YANCHENG  YCK', value: '盐城'},
		 {name: '泰州  TAI_ZHOU  TZS', value: '泰州  TAI_'},
		 {name: '宿迁  SUQIAN  SUQ', value: '宿迁'},
		 {name: '张家港  ZHANGJIAGANG  ZJG', value: '张家港'},
		 {name: '江阴  JIANGYIN  JIA', value: '江阴'},
		 {name: '丹阳  DANYANG  DNY', value: '丹阳'},
		 {name: '溧阳  LIYANG  LYR', value: '溧阳'},
		 {name: '泰兴  TAIXING  TXG', value: '泰兴'},
		 {name: '宜兴  YIXING  YIX', value: '宜兴'},
		 {name: '靖江  JINGJIANG  JGJ', value: '靖江'},
		 {name: '句容  JURONG  JRG', value: '句容'},
		 {name: '如皋  RUGAO  RGO', value: '如皋'},
		 {name: '扬中  YANGZHONG  YZG', value: '扬中'},
		 {name: '高邮  GAOYOU  GYO', value: '高邮'},
		 {name: '启东  QIDONG  QID', value: '启东'},
		 {name: '盱眙  XUYI  XUY', value: '盱眙'},
		 {name: '通州  TONGZHOU', value: '通州'},
		 {name: '金湖  JINHU  JHU', value: '金湖'},
		 {name: '浙江省  ZHEJIANG  ZJ', value: '浙江省'},
		 {name: '杭州  HANGZHOU  HGH', value: '杭州'},
		 {name: '上城区  SHANGCHENG  SCQ', value: '上城区'},
		 {name: '下城区  XAICHENG  XCG', value: '下城区'},
		 {name: '拱墅区  GONGSHU  GSQ', value: '拱墅区'},
		 {name: '西湖区  XIHU  XHQ', value: '西湖区'},
		 {name: '江干区  JIANGGAN  JGQ', value: '江干区'},
		 {name: '滨江区  BINJIANG  BJQ', value: '滨江区'},
		 {name: '萧山区  XIAOSHAN  XIS', value: '萧山区'},
		 {name: '余杭区  YUHANG  YHS', value: '余杭区'},
		 {name: '临安市  LINAN  LNA', value: '临安市'},
		 {name: '富阳区  FUYANG  FYZ', value: '富阳区'},
		 {name: '建德市  JIANDE  JDS', value: '建德市'},
		 {name: '桐庐县  TONGLU  TLU', value: '桐庐县'},
		 {name: '淳安县  CUNAN  CAZ', value: '淳安县'},
		 {name: '市郊  SHIJIAO  SWZ', value: '市郊'},
		 {name: '宁波  NINGBO  NGB', value: '宁波'},
		 {name: '海曙区  HAISHUQU  HNB', value: '海曙区'},
		 {name: '江东区  JIANGDONGQU  JDH', value: '江东区'},
		 {name: '江北区  JIANGBEIQU  JBE', value: '江北区'},
		 {name: '镇海区  ZHENHAIQU  ZHF', value: '镇海区'},
		 {name: '北仑区  BEILUNQU  BLN', value: '北仑区'},
		 {name: '鄞州区  YINZHOUQU', value: '鄞州区'},
		 {name: '余姚市  YUYAOSHI  YYO', value: '余姚市'},
		 {name: '慈溪市  CIXISHI  CXI', value: '慈溪市'},
		 {name: '奉化市  FENGHUASHI  FHU', value: '奉化市'},
		 {name: '象山县  XIANGSHANXIAN', value: '象山县'},
		 {name: '宁海县  NINGHAIXIAN  NHI', value: '宁海县'},
		 {name: '温州  WENZHOU  WNZ', value: '温州'},
		 {name: '鹿城区  LUCHENGQU  LUW', value: '鹿城区'},
		 {name: '龙湾区  LONGWANQU  LWW', value: '龙湾区'},
		 {name: '瓯海区  OUHAIQU  OHQ', value: '瓯海区'},
		 {name: '瑞安市  RUIANSHI  RAS', value: '瑞安市'},
		 {name: '乐清市  LEQINGSHI  YQZ', value: '乐清市'},
		 {name: '洞头县  DONGTOUXIAN  DTO', value: '洞头县'},
		 {name: '永嘉县  YONGJIAXIAN  YJX', value: '永嘉县'},
		 {name: '平阳县  PINGYANGXIAN  PYG', value: '平阳县'},
		 {name: '苍南县  CANGNANXIAN  CAN', value: '苍南县'},
		 {name: '文成县  WENCHENGXIAN  WCZ', value: '文成县'},
		 {name: '泰顺县  TAISHUNXIAN  TSZ', value: '泰顺县'},
		 {name: '绍兴  SHAOXING', value: '绍兴'},
		 {name: '金华  JINHUA', value: '金华'},
		 {name: '台州  TAIZHOU  TZZ', value: '台州'},
		 {name: '湖州  HUZHOU  HZH', value: '湖州'},
		 {name: '嘉兴  JIAXING  JIX', value: '嘉兴'},
		 {name: '衢州  QUZHOU  QUZ', value: '衢州'},
		 {name: '丽水  LISHUI', value: '丽水'},
		 {name: '舟山  ZHOUSHAN  ZOS', value: '舟山'},
		 {name: '义乌  YIWU  YWS', value: '义乌'},
		 {name: '海宁  HAINING  HNG', value: '海宁'},
		 {name: '玉环县  YUHUANXIAN  YHN', value: '玉环县'},
		 {name: '平湖  PINGHU  PHU', value: '平湖'},
		 {name: '永康  YONGKANG  YKG', value: '永康'},
		 {name: '东阳  DONGYANG  DGY', value: '东阳'},
		 {name: '嘉善  JIASHAN  JSK', value: '嘉善'},
		 {name: '余姚  YUYAO  YYO', value: '余姚'},
		 {name: '慈溪  CIXI  CXI', value: '慈溪'},
		 {name: '乐清  LEQING  YQZ', value: '乐清'},
		 {name: '永嘉  YONGJIA  YJX', value: '永嘉'},
		 {name: '桐乡  TONGXIANG  TXZ', value: '桐乡'},
		 {name: '瑞安  RUIAN  RAS', value: '瑞安'},
		 {name: '温岭  WENLING  WLS', value: '温岭'},
		 {name: '上虞  SHANGYU  SYZ', value: '上虞'},
		 {name: '诸暨  ZHUJI  ZHJ', value: '诸暨'},
		 {name: '宁海  NINGHAI  NHI', value: '宁海'},
		 {name: '三门  SANMEN', value: '三门'},
		 {name: '德清  DEQING  DQX', value: '德清'},
		 {name: '象山  XIANGSHAN', value: '象山'},
		 {name: '方家山  FANGJIASHAN', value: '方家山'},
		 {name: '龙泉  LONGQUAN', value: '龙泉'},
		 {name: '安徽省  ANHUI  AH', value: '安徽省'},
		 {name: '合肥  HEFEI  HFE', value: '合肥'},
		 {name: '庐阳区  LUYANGQU', value: '庐阳区'},
		 {name: '瑶海区  YAOHAIQU', value: '瑶海区'},
		 {name: '蜀山区  SHUSHANQU', value: '蜀山区'},
		 {name: '包河区  BAOHEQU', value: '包河区'},
		 {name: '长丰县  CHANGFENGXIAN  CFG', value: '长丰县'},
		 {name: '肥东县  FEIDONGXIAN  FDO', value: '肥东县'},
		 {name: '肥西县  FEIXIXIAN  FIX', value: '肥西县'},
		 {name: '新站区  XINZHANQU', value: '新站区'},
		 {name: '经开区  JINGKAIQU', value: '经开区'},
		 {name: '高新区  GAOXINQU', value: '高新区'},
		 {name: '滨湖区  BINHUXINQU', value: '滨湖区'},
		 {name: '北城区  BEICHENGXINQU', value: '北城区'},
		 {name: '政务区  ZHENGWUXINQU', value: '政务区'},
		 {name: '安庆  ANQING  AQG', value: '安庆'},
		 {name: '蚌埠  BENGBU  BBU', value: '蚌埠'},
		 {name: '芜湖  WUHU', value: '芜湖'},
		 {name: '淮南  HUAINAN  HNS', value: '淮南'},
		 {name: '马鞍山  MAANSHAN  MAA', value: '马鞍山'},
		 {name: '淮北  HUAIBEI  HBE', value: '淮北'},
		 {name: '铜陵  TONGLING', value: '铜陵'},
		 {name: '黄山  HUANGSHAN', value: '黄山'},
		 {name: '滁州  CHUZHOU  CUZ', value: '滁州'},
		 {name: '阜阳  FUYANG  FYS', value: '阜阳'},
		 {name: '宿州  SU_ZHOU  SUZ', value: '宿州  SU_'},
		 {name: '六安  LIUAN', value: '六安'},
		 {name: '亳州  BOZHOU  BOZ', value: '亳州'},
		 {name: '池州  CHIZHOU  CZD', value: '池州'},
		 {name: '宣城  XUANCHENG  XCD', value: '宣城'},
		 {name: '巢湖  CHAOHU', value: '巢湖'},
		 {name: '凤阳  FENGYANG  FYG', value: '凤阳'},
		 {name: '广德  GUANGDE  GGD', value: '广德'},
		 {name: '宿松  SUSONG  SUS', value: '宿松'},
		 {name: '福建省  FUJIAN  FJ', value: '福建省'},
		 {name: '福州  FUZHOU  FOC', value: '福州'},
		 {name: '鼓楼区  GULOUQU  GLK', value: '鼓楼区'},
		 {name: '台江区  TAIJIANGQU', value: '台江区'},
		 {name: '仓山区  CANGSHANQU  CSQ', value: '仓山区'},
		 {name: '马尾区  MAWEIQU  MWQ', value: '马尾区'},
		 {name: '晋安区  JINANQU  JAF', value: '晋安区'},
		 {name: '福清市  FUQINGSHI  FQS', value: '福清市'},
		 {name: '长乐市  CHANGLESHI  CLS', value: '长乐市'},
		 {name: '闽侯县  MINHOUXIAN  MHO', value: '闽侯县'},
		 {name: '连江县  LIANJIANGXIAN  LJF', value: '连江县'},
		 {name: '罗源县  LUOYUANXIAN  LOY', value: '罗源县'},
		 {name: '闽清县  MINQINGXIAN  MQG', value: '闽清县'},
		 {name: '永泰县  YONGTAIXIAN  YTX', value: '永泰县'},
		 {name: '平潭县  PINGTANXIAN  PTN', value: '平潭县'},
		 {name: '泉州  QUANZHOU  QZJ', value: '泉州'},
		 {name: '厦门  XIAMEN  XMN', value: '厦门'},
		 {name: '思明区  SIMINGQU  SMQ', value: '思明区'},
		 {name: '海沧区  HAICANGQU', value: '海沧区'},
		 {name: '湖里区  HULIQU  HLQ', value: '湖里区'},
		 {name: '集美区  JIMEIQU  JMQ', value: '集美区'},
		 {name: '同安区  TONGANQU  TAQ', value: '同安区'},
		 {name: '翔安区  XIANGANQU', value: '翔安区'},
		 {name: '漳州  ZHANGZHOU  ZZU', value: '漳州'},
		 {name: '莆田  PUTIAN', value: '莆田'},
		 {name: '三明  SANMING  SMS', value: '三明'},
		 {name: '南平  NANPING  NPS', value: '南平'},
		 {name: '龙岩  LONGYAN  LYF', value: '龙岩'},
		 {name: '宁德  NINGDE', value: '宁德'},
		 {name: '泉港区  QUANGANGQU', value: '泉港区'},
		 {name: '福安  FUAN  FAS', value: '福安'},
		 {name: '晋江  JINJIANG  JJG', value: '晋江'},
		 {name: '甘肃省  GANSU  GS', value: '甘肃省'},
		 {name: '兰州  LANZHOU  LHW', value: '兰州'},
		 {name: '皋兰县  GAOLANXIAN  GAL', value: '皋兰县'},
		 {name: '城关区  CHENGGUANQU  CLZ', value: '城关区'},
		 {name: '七里河  QILIHEQU  QLH', value: '七里河'},
		 {name: '西固区  XIGUQU  XGU', value: '西固区'},
		 {name: '安宁区  ANNINGQU', value: '安宁区'},
		 {name: '红古区  HONGGUQU  HOG', value: '红古区'},
		 {name: '永登县  YONGDENGXIAN  YDG', value: '永登县'},
		 {name: '榆中县  YUZHONGXIAN  YZX', value: '榆中县'},
		 {name: '嘉峪关  JIAYUGUAN  JYG', value: '嘉峪关'},
		 {name: '酒泉  JIUQUAN', value: '酒泉'},
		 {name: '金昌  JINCHANG  JCS', value: '金昌'},
		 {name: '白银  BAIYIN', value: '白银'},
		 {name: '天水  TIANSHUI  TSU', value: '天水'},
		 {name: '张掖  ZHANGYE', value: '张掖'},
		 {name: '武威  WUWEI', value: '武威'},
		 {name: '定西  DINGXI', value: '定西'},
		 {name: '陇南  LONGNAN  LND', value: '陇南'},
		 {name: '平凉  PINGLIANG', value: '平凉'},
		 {name: '庆阳  QINGYANG', value: '庆阳'},
		 {name: '临夏  LINXIA', value: '临夏'},
		 {name: '甘南  GANNAN', value: '甘南'},
		 {name: '广西  GUANGXI  GX', value: '广西'},
		 {name: '南宁  NANNING', value: '南宁'},
		 {name: '邕宁区  YONGNINGQU  YNG', value: '邕宁区'},
		 {name: '青秀区  QINGXIUQU', value: '青秀区'},
		 {name: '兴宁区  XINGNINGQU', value: '兴宁区'},
		 {name: '良庆区  LIANGQINGQU', value: '良庆区'},
		 {name: '西乡塘  XIXIANGTANGQU  XXA', value: '西乡塘'},
		 {name: '江南区  JIANGNANQU  JNA', value: '江南区'},
		 {name: '武鸣县  WUMINGXIAN  WMG', value: '武鸣县'},
		 {name: '隆安县  LONGANXIAN  LGA', value: '隆安县'},
		 {name: '马山县  MASHANXIAN', value: '马山县'},
		 {name: '上林县  SHANGLINXIAN  SLX', value: '上林县'},
		 {name: '宾阳县  BINYANGXIAN  BYX', value: '宾阳县'},
		 {name: '横县  HENGXIAN  HEN', value: '横县'},
		 {name: '北海  BEIHAI  BHY', value: '北海'},
		 {name: '桂林  GUILIN  KWL', value: '桂林'},
		 {name: '柳州  LIUZHOU  LZ', value: '柳州'},
		 {name: '玉林  YULIN  YUL', value: '玉林'},
		 {name: '梧州  WUZHOU  WUZ', value: '梧州'},
		 {name: '崇左  CHONGZUO  CZU', value: '崇左'},
		 {name: '来宾  LAIBIN  LBN', value: '来宾'},
		 {name: '防城港  FANGCHENGGANG  FCG', value: '防城港'},
		 {name: '百色  BAISE  BS', value: '百色'},
		 {name: '钦州  QINZHOU  QZH', value: '钦州'},
		 {name: '贺州  HEZHOU  HZ', value: '贺州'},
		 {name: '河池  HECHI  HC', value: '河池'},
		 {name: '贵港  GUIGANG  GUG', value: '贵港'},
		 {name: '贵州省  GUIZHOU  GZ', value: '贵州省'},
		 {name: '贵阳  GUIYANG  KWE', value: '贵阳'},
		 {name: '南明区  NANMINGQU  NMQ', value: '南明区'},
		 {name: '云岩区  YUNYANQU  YYQ', value: '云岩区'},
		 {name: '花溪区  HUAXIQU  HXI', value: '花溪区'},
		 {name: '乌当区  WUDANGQU  WDQ', value: '乌当区'},
		 {name: '白云区  BAIYUNQU  BY', value: '白云区'},
		 {name: '小河区  XIAOHEQU  XH', value: '小河区'},
		 {name: '金阳区  JINYANGXINQU  JYW', value: '金阳区'},
		 {name: '新天园  XINTIANYUANQU  XTY', value: '新天园'},
		 {name: '清镇市  QINGZHENSHI  QZN', value: '清镇市'},
		 {name: '开阳县  KAIYANGXIAN  KYG', value: '开阳县'},
		 {name: '修文县  XIUWENXIAN  XWX', value: '修文县'},
		 {name: '息烽县  XIFENGXIAN  XFX', value: '息烽县'},
		 {name: '遵义  ZUNYI  ZY', value: '遵义'},
		 {name: '六盘水  LIUPANSHUI  LPS', value: '六盘水'},
		 {name: '安顺  ANSHUN  AS', value: '安顺'},
		 {name: '毕节  BIJIE  BIJ', value: '毕节'},
		 {name: '铜仁  TONGREN  TR', value: '铜仁'},
		 {name: '黔西南  QIANXINAN  QXN', value: '黔西南'},
		 {name: '黔东南  QIANDONGNAN  QNDN', value: '黔东南'},
		 {name: '黔南  QIANNAN  QNZ', value: '黔南'},
		 {name: '海南省  HAINAN  HN', value: '海南省'},
		 {name: '海口  HAIKOU  HAK', value: '海口'},
		 {name: '秀英区  XIUYINGQU  XYH', value: '秀英区'},
		 {name: '龙华区  LONGHUAQU  LH', value: '龙华区'},
		 {name: '琼山区  QIONGSHANQU  QSS', value: '琼山区'},
		 {name: '美兰区  MEILANQU  ML', value: '美兰区'},
		 {name: '澄迈县  CHENGMAIXIAN  CMA', value: '澄迈县'},
		 {name: '万宁市  WANNINGSHI  WNN', value: '万宁市'},
		 {name: '文昌市  WENCHANGSHI  WEC', value: '文昌市'},
		 {name: '儋州市  DANZHOUSHI  DNZ', value: '儋州市'},
		 {name: '屯昌县  TUNCHANGXIAN  TCG', value: '屯昌县'},
		 {name: '东方市  DONGFANGSHI  DFG', value: '东方市'},
		 {name: '昌江县  CHANGJIANGXIAN  CJX', value: '昌江县'},
		 {name: '乐东黎  LEDONGLIMIAOZIZHIXIAN  LED', value: '乐东黎'},
		 {name: '临高县  LINGAOXIAN  LGO', value: '临高县'},
		 {name: '琼海市  QIONGHAISHI  QHA', value: '琼海市'},
		 {name: '府城  FUCHENG  FC', value: '府城'},
		 {name: '三亚  SANYA  SYX', value: '三亚'},
		 {name: '三沙  SANSHA  SS', value: '三沙'},
		 {name: '文昌  WENCHANG  WEC', value: '文昌'},
		 {name: '琼海  QIONGHAI  QHA', value: '琼海'},
		 {name: '万宁  WANNING  WNN', value: '万宁'},
		 {name: '儋州  DANZHOU  DNZ', value: '儋州'},
		 {name: '东方  DONGFANG  DFG', value: '东方'},
		 {name: '五指山  WUZHISHAN  WZS', value: '五指山'},
		 {name: '定安  DINGAN  DIA', value: '定安'},
		 {name: '屯昌  TUNCHANG  TCG', value: '屯昌'},
		 {name: '澄迈  CHENGMAI  CMA', value: '澄迈'},
		 {name: '临高  LINGAO  LGO', value: '临高'},
		 {name: '琼中  QIONGZHONG  QZG', value: '琼中'},
		 {name: '保亭  BAOTING  BTG', value: '保亭'},
		 {name: '白沙  BAISHA  BSX', value: '白沙'},
		 {name: '昌江  CHANGJIANG  CJ', value: '昌江'},
		 {name: '乐东  LEDONG  LED', value: '乐东'},
		 {name: '陵水  LINGSHUI  LSL', value: '陵水'},
		 {name: '河北省  HEBEI', value: '河北省'},
		 {name: '石家庄  SHIJIAZHUANG  SJW', value: '石家庄'},
		 {name: '长安区  CHANGANQU  CAQ', value: '长安区'},
		 {name: '桥东区  QIAODONGQU  QDZ', value: '桥东区'},
		 {name: '桥西区  QIAOXIQU  QXI', value: '桥西区'},
		 {name: '新华区  XINHUAQU  XHH', value: '新华区'},
		 {name: '裕华区  YUHUAQU  YHQ', value: '裕华区'},
		 {name: '井陉矿  JINGXINGKUANGQU  JXG', value: '井陉矿'},
		 {name: '高新区  GAOXINQU  GXQ', value: '高新区'},
		 {name: '辛集市  XINJISHI  XJS', value: '辛集市'},
		 {name: '藁城市  GAOCHENGSHI  GCS', value: '藁城市'},
		 {name: '晋州市  JINZHOUSHI  JZJ', value: '晋州市'},
		 {name: '新乐市  XINLESHI  XLE', value: '新乐市'},
		 {name: '鹿泉市  LUQUANSHI  LUQ', value: '鹿泉市'},
		 {name: '井陉县  JINGXINGXIAN  JJX', value: '井陉县'},
		 {name: '正定县  ZHENGDINGXIAN  ZDJ', value: '正定县'},
		 {name: '栾城县  LUANCHENGXIAN  LCG', value: '栾城县'},
		 {name: '行唐县  XINGTANGXIAN  XTG', value: '行唐县'},
		 {name: '灵寿县  LINGSHOUXIAN  LSO', value: '灵寿县'},
		 {name: '高邑县  GAOYIXIAN  GYJ', value: '高邑县'},
		 {name: '深泽县  SHENZEXIAN  SZX', value: '深泽县'},
		 {name: '赞皇县  ZANHUANGXIAN  ZHG', value: '赞皇县'},
		 {name: '无极县  WUJIXIAN  WJI', value: '无极县'},
		 {name: '平山县  PINGSHANXIAN', value: '平山县'},
		 {name: '元氏县  YUANSHIXIAN  YSI', value: '元氏县'},
		 {name: '赵县  ZHAOXIAN  ZAO', value: '赵县'},
		 {name: '保定  BAODING  BDS', value: '保定'},
		 {name: '承德  CHENGDE  CD', value: '承德'},
		 {name: '邯郸  HANDAN  HD', value: '邯郸'},
		 {name: '廊坊  LANGFANG  LFS', value: '廊坊'},
		 {name: '秦皇岛  QINHUANGDAO  SHP', value: '秦皇岛'},
		 {name: '唐山  TANGSHAN  TGS', value: '唐山'},
		 {name: '张家口  ZHANGJIAKOU  ZJK', value: '张家口'},
		 {name: '邢台  XINGTAI  XT', value: '邢台'},
		 {name: '沧州  CANGZHOU  CGZ', value: '沧州'},
		 {name: '衡水  HENGSHUI  HGS', value: '衡水'},
		 {name: '燕郊  YANJIAO  YJ', value: '燕郊'},
		 {name: '固安  GUAN  GUA', value: '固安'},
		 {name: '遵化  ZUNHUA  ZNH', value: '遵化'},
		 {name: '香河  XIANGHE  XGH', value: '香河'},
		 {name: '三河  SANHE  SNH', value: '三河'},
		 {name: '河南省  HENAN  HEN', value: '河南省'},
		 {name: '郑州  ZHENGZHOU  CGO', value: '郑州'},
		 {name: '金水区  JINSHUIQU  JSU', value: '金水区'},
		 {name: '邙山区  MANGSHANQU  MSQ', value: '邙山区'},
		 {name: '二七区  ERQIQU  EQQ', value: '二七区'},
		 {name: '管城区  GUANCHENGQU  GCH', value: '管城区'},
		 {name: '中原区  ZHONGYUANQU  ZYQ', value: '中原区'},
		 {name: '上街区  SHANGJIEQU  SJE', value: '上街区'},
		 {name: '惠济区  HUIJIQU  HJQ', value: '惠济区'},
		 {name: '郑东区  ZHENGDONGXINQU  ZDQ', value: '郑东区'},
		 {name: '经济区  JINGJIJISHUKAIFAQU  JJQ', value: '经济区'},
		 {name: '高新区  GAOXINKAIFAQU  GXQ', value: '高新区'},
		 {name: '加工区  CHUKOUJIAGONGQU  JGQ', value: '加工区'},
		 {name: '巩义市  GONGYISHI  GYI', value: '巩义市'},
		 {name: '荥阳市  YINGYANGSHI  XYK', value: '荥阳市'},
		 {name: '新密市  XINMISHI  XMI', value: '新密市'},
		 {name: '新郑市  XINZHENGSHI  XZG', value: '新郑市'},
		 {name: '登封市  DENGFENGSHI', value: '登封市'},
		 {name: '中牟县  ZHONGMOUXIAN  ZMO', value: '中牟县'},
		 {name: '开封  KAIFENG  KF', value: '开封'},
		 {name: '洛阳  LUOYANG  LYA', value: '洛阳'},
		 {name: '商丘  SHANGQIU  SQS', value: '商丘'},
		 {name: '安阳  ANYANG  AY', value: '安阳'},
		 {name: '平顶山  PINGDINGSHAN  PDS', value: '平顶山'},
		 {name: '新乡  XINXIANG  XXA', value: '新乡'},
		 {name: '焦作  JIAOZUO  JZY', value: '焦作'},
		 {name: '濮阳  PUYANG  PY', value: '濮阳'},
		 {name: '许昌  XUCHANG  XC', value: '许昌'},
		 {name: '漯河  LUOHE  LHS', value: '漯河'},
		 {name: '三门峡  SHANMENXIA  SMX', value: '三门峡'},
		 {name: '鹤壁  HEBI  HBS', value: '鹤壁'},
		 {name: '周口  ZHOUKOU  ZK', value: '周口'},
		 {name: '驻马店  ZHUMADIAN  ZMD', value: '驻马店'},
		 {name: '南阳  NANYANG  NYS', value: '南阳'},
		 {name: '信阳  XINYANG  XYG', value: '信阳'},
		 {name: '济源  JIYUAN  JYY', value: '济源'},
		 {name: '西平  XIPING  XIP', value: '西平'},
		 {name: '长葛  CHANGGE  CGE', value: '长葛'},
		 {name: '黑龙江省  HEILONGJIANG  HL', value: '黑龙江省'},
		 {name: '哈尔滨  HAERBIN  HRB', value: '哈尔滨'},
		 {name: '道里区  DAOLIQU  DLH', value: '道里区'},
		 {name: '南岗区  NANGANGQU  NGQ', value: '南岗区'},
		 {name: '动力区  DONGLIQU  DGL', value: '动力区'},
		 {name: '平房区  PINGFANGQU  PFQ', value: '平房区'},
		 {name: '香坊区  XIANGFANGQU  XFQ', value: '香坊区'},
		 {name: '太平区  TAIPINGQU  TPQ', value: '太平区'},
		 {name: '道外区  DAOWAIQU  DWQ', value: '道外区'},
		 {name: '阿城市  ACHENGSHI  ACG', value: '阿城市'},
		 {name: '呼兰区  HULANQU  HLH', value: '呼兰区'},
		 {name: '松北区  SONGBEIQU', value: '松北区'},
		 {name: '尚志市  SHANGZHISHI  SZI', value: '尚志市'},
		 {name: '双城市  SHUANGCHENGSHI  SCS', value: '双城市'},
		 {name: '五常市  WUCHANGSHI  WCA', value: '五常市'},
		 {name: '方正县  FANGZHENGXIAN  FZH', value: '方正县'},
		 {name: '宾县  BINXIAN  BNX', value: '宾县'},
		 {name: '依兰县  YILANXIAN  YLH', value: '依兰县'},
		 {name: '巴彦县  BAYANXIAN', value: '巴彦县'},
		 {name: '通河县  TONGHEXIAN  TOH', value: '通河县'},
		 {name: '木兰县  MULANXIAN  MUL', value: '木兰县'},
		 {name: '延寿县  YANSHOUXIAN  YSU', value: '延寿县'},
		 {name: '大庆  DAQING  DQG', value: '大庆'},
		 {name: '佳木斯  JIAMUSI  JMU', value: '佳木斯'},
		 {name: '牡丹江  MUDANJIANG  MDG', value: '牡丹江'},
		 {name: '齐齐哈尔  QIQIHAER  NDG', value: '齐齐哈尔'},
		 {name: '鸡西  JIXI  JXI', value: '鸡西'},
		 {name: '鹤岗  HEGANG  HEG', value: '鹤岗'},
		 {name: '双鸭山  SHUANGYASHAN  SYS', value: '双鸭山'},
		 {name: '伊春  YICHUN', value: '伊春'},
		 {name: '七台河  QITAIHE  QTH', value: '七台河'},
		 {name: '黑河  HEIHE  HEK', value: '黑河'},
		 {name: '绥化  SUIHUA', value: '绥化'},
		 {name: '大兴安岭  DAXINGANLING', value: '大兴安岭'},
		 {name: '安达  ANDA  ADA', value: '安达'},
		 {name: '双城  SHUANGCHENG  SCS', value: '双城'},
		 {name: '尚志  SHANGZHI  SZI', value: '尚志'},
		 {name: '绥芬河  SUIFENGHE  SFE', value: '绥芬河'},
		 {name: '肇东  ZHAODONG  ZDS', value: '肇东'},
		 {name: '湖北省  HUBEI  HB', value: '湖北省'},
		 {name: '武汉  WUHAN  WUH', value: '武汉'},
		 {name: '江岸区  JIANGAN  JAA', value: '江岸区'},
		 {name: '江汉区  JIANGHAN  JHN', value: '江汉区'},
		 {name: '硚口区  QIAOKOU  QKQ', value: '硚口区'},
		 {name: '汉阳区  HANYANG  HYA', value: '汉阳区'},
		 {name: '武昌区  WUCHANG  WCQ', value: '武昌区'},
		 {name: '青山区  QINGSHAN  QSN', value: '青山区'},
		 {name: '洪山区  HONGSHAN  HSQ', value: '洪山区'},
		 {name: '蔡甸区  CAIDIAN  CDN', value: '蔡甸区'},
		 {name: '江夏区  JIANGXIA  JXQ', value: '江夏区'},
		 {name: '黄陂区  HUANGPI  HPI', value: '黄陂区'},
		 {name: '新洲区  XINZHOU  XNZ', value: '新洲区'},
		 {name: '东西湖  DONGXIHU  DXH', value: '东西湖'},
		 {name: '汉南区  HANNAN  HNQ', value: '汉南区'},
		 {name: '开发区  JINGJIKAIFAQU', value: '开发区'},
		 {name: '十堰  SHIYAN  SYE', value: '十堰'},
		 {name: '襄阳  XIANGYANG  XYA', value: '襄阳'},
		 {name: '宜昌  YICHANG', value: '宜昌'},
		 {name: '潜江  QIANJIANG  QNJ', value: '潜江'},
		 {name: '荆门  JINGMEN  JMS', value: '荆门'},
		 {name: '荆州  JINGZHOU', value: '荆州'},
		 {name: '黄石  HUANGSHI', value: '黄石'},
		 {name: '鄂州  EZHOU  EZS', value: '鄂州'},
		 {name: '黄冈  HUANGGANG  HE', value: '黄冈'},
		 {name: '孝感  XIAOGAN  XGE', value: '孝感'},
		 {name: '咸宁  XIANNING  XNS', value: '咸宁'},
		 {name: '随州  SUIZHOU  SZR', value: '随州'},
		 {name: '仙桃  XIANTAO  XNT', value: '仙桃'},
		 {name: '天门  TIANMEN  TMS', value: '天门'},
		 {name: '神农架  SHENNONGJIA  SNJ', value: '神农架'},
		 {name: '恩施  ENSHI', value: '恩施'},
		 {name: '公安  GONGAN  GGA', value: '公安'},
		 {name: '武穴  WUXUE  WXE', value: '武穴'},
		 {name: '宜城  YICHENG  YCW', value: '宜城'},
		 {name: '湖南省  HUNAN  HN', value: '湖南省'},
		 {name: '长沙  CHANGSHA', value: '长沙'},
		 {name: '岳麓区  YUELUQU  YLU', value: '岳麓区'},
		 {name: '芙蓉区  FURONGQU  FRQ', value: '芙蓉区'},
		 {name: '天心区  TIANXINQU  TXQ', value: '天心区'},
		 {name: '开福区  KAIFUQU  KFQ', value: '开福区'},
		 {name: '雨花区  YUHUAQU', value: '雨花区'},
		 {name: '开发区  KAIFAQU', value: '开发区'},
		 {name: '浏阳市  LIUYANGSHI  LYS', value: '浏阳市'},
		 {name: '长沙县  CHANGSHAXIAN', value: '长沙县'},
		 {name: '望城区  WANGCHENGQU  WCH', value: '望城区'},
		 {name: '宁乡县  NINGXIANGXIAN  NXX', value: '宁乡县'},
		 {name: '湘潭  XIANGTAN', value: '湘潭'},
		 {name: '株洲  ZHUZHOU', value: '株洲'},
		 {name: '常德  CHANGDE  CDE', value: '常德'},
		 {name: '衡阳  HENGYANG', value: '衡阳'},
		 {name: '益阳  YIYANG  YYS', value: '益阳'},
		 {name: '郴州  CHENZHOU  CNZ', value: '郴州'},
		 {name: '岳阳  YUEYANG', value: '岳阳'},
		 {name: '邵阳  SHAOYANG', value: '邵阳'},
		 {name: '张家界  ZHANGJIAJIE  ZJJ', value: '张家界'},
		 {name: '娄底  LOUDI', value: '娄底'},
		 {name: '永州  YONGZHOU  YZS', value: '永州'},
		 {name: '怀化  HUAIHUA  HHS', value: '怀化'},
		 {name: '湘西  XIANGXI  XXZ', value: '湘西'},
		 {name: '吉林省  JILIN', value: '吉林省'},
		 {name: '长春  CHANGCHUN  CGQ', value: '长春'},
		 {name: '朝阳区  CHAOYANGQU', value: '朝阳区'},
		 {name: '宽城区  KUANCHENGQU', value: '宽城区'},
		 {name: '二道区  ERDAOQU', value: '二道区'},
		 {name: '南关区  NANGUANQU  NGK', value: '南关区'},
		 {name: '绿园区  LVYUANQU  LYQ', value: '绿园区'},
		 {name: '双阳区  SHUANGYANGQU  SYQ', value: '双阳区'},
		 {name: '净月区  JINGYUETANKAIFAQU', value: '净月区'},
		 {name: '高新区  GAOXINQU', value: '高新区'},
		 {name: '经开区  JINGKAIQU', value: '经开区'},
		 {name: '汽开区  QICHECHANYEKAIFAQU', value: '汽开区'},
		 {name: '德惠市  DEHUISHI  DEH', value: '德惠市'},
		 {name: '九台市  JIUTAISHI  JUT', value: '九台市'},
		 {name: '榆树市  YUSHUSHI  YSS', value: '榆树市'},
		 {name: '农安县  NONGANXIAN  NAJ', value: '农安县'},
		 {name: '高新区  GAOXINKAIFAQU', value: '高新区'},
		 {name: '经济区  JINGJIKAIFAQU', value: '经济区'},
		 {name: '净月区  JINGYUEKAIFAQU', value: '净月区'},
		 {name: '吉林市  JINLINSHI', value: '吉林市'},
		 {name: '四平  SIPING  SPS', value: '四平'},
		 {name: '辽源  LIAOYUAN  LYH', value: '辽源'},
		 {name: '通化  TONGHUAN', value: '通化'},
		 {name: '白山  BAISHAN  BSN', value: '白山'},
		 {name: '松原  SONGYUAN  SYU', value: '松原'},
		 {name: '白城  BAICHENG  BCS', value: '白城'},
		 {name: '延吉  YANJI  YNJ', value: '延吉'},
		 {name: '延边  YANBIAN  YBZ', value: '延边'},
		 {name: '公主岭  GONGZHULING  GZL', value: '公主岭'},
		 {name: '江西省  JIANGXI  JX', value: '江西省'},
		 {name: '南昌  NANCHANG', value: '南昌'},
		 {name: '东湖区  DONGHUQU  DHU', value: '东湖区'},
		 {name: '西湖区  XIHUQU  XHQ', value: '西湖区'},
		 {name: '青云谱  QINGYUNPUQU  QYP', value: '青云谱'},
		 {name: '湾里区  WANLIQU  WLI', value: '湾里区'},
		 {name: '青山湖  QINGSHANHUQU  QSN', value: '青山湖'},
		 {name: '红谷滩  HONGGUTANXINQU', value: '红谷滩'},
		 {name: '昌北区  CHANGBEIQU', value: '昌北区'},
		 {name: '高新区  GAOXINQU', value: '高新区'},
		 {name: '南昌县  NANCHANGXIAN', value: '南昌县'},
		 {name: '新建县  XINJIANXIAN  XJN', value: '新建县'},
		 {name: '安义县  ANYIXIAN  AYI', value: '安义县'},
		 {name: '进贤县  JINXIANXIAN  JXX', value: '进贤县'},
		 {name: '桑海区  SANGHAIKAIFAQU', value: '桑海区'},
		 {name: '九江  JIUJIANG', value: '九江'},
		 {name: '赣州  GANZHOU  GZH', value: '赣州'},
		 {name: '宜春  YI_CHUN', value: '宜春  YI_'},
		 {name: '吉安  JIAN', value: '吉安'},
		 {name: '上饶  SHANGRAO', value: '上饶'},
		 {name: '抚州  FU_ZHOU  FZD', value: '抚州  FU_'},
		 {name: '景德镇  JINGDEZHEN  JDZ', value: '景德镇'},
		 {name: '萍乡  PINGXIANG  PXS', value: '萍乡'},
		 {name: '新余  XINYU  XYU', value: '新余'},
		 {name: '鹰潭  YINGTAN  YTS', value: '鹰潭'},
		 {name: '辽宁省  LIAONING  LN', value: '辽宁省'},
		 {name: '沈阳  SHENYANG  SHE', value: '沈阳'},
		 {name: '沈河区  SHENHEQU  SHQ', value: '沈河区'},
		 {name: '皇姑区  HUANGGUQU  HGU', value: '皇姑区'},
		 {name: '和平区  HEPINGQU', value: '和平区'},
		 {name: '大东区  DADONGQU  DDQ', value: '大东区'},
		 {name: '铁西区  TIEXIQU  TXA', value: '铁西区'},
		 {name: '苏家屯  SUJIATUNQU  SJT', value: '苏家屯'},
		 {name: '东陵区  DONGLINGQU  DLQ', value: '东陵区'},
		 {name: '沈北区  SHENBEIXINQU', value: '沈北区'},
		 {name: '于洪区  YUHONGQU  YHQ', value: '于洪区'},
		 {name: '浑南区  HUNNANXINQU', value: '浑南区'},
		 {name: '新民市  XINMINSHI  XMS', value: '新民市'},
		 {name: '辽中县  LIAOZHONGXIAN  LZL', value: '辽中县'},
		 {name: '康平县  KANGPINGXIAN  KPG', value: '康平县'},
		 {name: '法库县  FAKUXIAN  FKU', value: '法库县'},
		 {name: '鞍山  ANSHAN  ASN', value: '鞍山'},
		 {name: '大连  DALIAN  DLC', value: '大连'},
		 {name: '西岗区  XIGANG  XGD', value: '西岗区'},
		 {name: '中山区  ZHONGSHAN', value: '中山区'},
		 {name: '沙河口  SHAHEQU', value: '沙河口'},
		 {name: '甘井子  GANJINGZI  GJZ', value: '甘井子'},
		 {name: '旅顺口  LVSHUNKOU  LSK', value: '旅顺口'},
		 {name: '金州区  JINZHOU  JZH', value: '金州区'},
		 {name: '瓦房店  WAFANGDIAN  WFD', value: '瓦房店'},
		 {name: '普兰店  PULANDIAN', value: '普兰店'},
		 {name: '庄河市  ZHUANGHE  ZHH', value: '庄河市'},
		 {name: '普湾区  PUWANXINQU', value: '普湾区'},
		 {name: '长海县  CHANGHAIXIAN  CHX', value: '长海县'},
		 {name: '新区  XINQU  XNQ', value: '新区'},
		 {name: '开发区  KAIFAQU', value: '开发区'},
		 {name: '葫芦岛  HULUDAO  HLD', value: '葫芦岛'},
		 {name: '抚顺  FUSHUN', value: '抚顺'},
		 {name: '本溪  BENXI', value: '本溪'},
		 {name: '丹东  DANDONG  DDG', value: '丹东'},
		 {name: '锦州  JINZHOU  JNZ', value: '锦州'},
		 {name: '营口  YINGKOU  YIK', value: '营口'},
		 {name: '阜新  FUXIN', value: '阜新'},
		 {name: '辽阳  LIAOYANG', value: '辽阳'},
		 {name: '盘锦  PANJIN  PJS', value: '盘锦'},
		 {name: '铁岭  TIELING', value: '铁岭'},
		 {name: '朝阳  CHAOYANG', value: '朝阳'},
		 {name: '兴城  XINGCHENG  XCL', value: '兴城'},
		 {name: '海城  HAICHENG', value: '海城'},
		 {name: '昌图  CHANGTU  CTX', value: '昌图'},
		 {name: '开原  KAIYUAN  KYS', value: '开原'},
		 {name: '内蒙古  NEIMENGGU  NM', value: '内蒙古'},
		 {name: '呼和浩特  HUHEHAOTE  Hhht', value: '呼和浩特'},
		 {name: '回民区  HUIMINQU  HMQ', value: '回民区'},
		 {name: '玉泉区  YUQUANQU  YQN', value: '玉泉区'},
		 {name: '新城区  XINCHENGQU', value: '新城区'},
		 {name: '赛罕区  SAIHANQU', value: '赛罕区'},
		 {name: '清水河  QINGSHUIHEXIAN', value: '清水河'},
		 {name: '土左旗  TUMOTEZUOQI', value: '土左旗'},
		 {name: '托克托  TUOKETUOXIAN  TOG', value: '托克托'},
		 {name: '格尔县  HELINGEERXIAN  GOS', value: '格尔县'},
		 {name: '武川县  WUCHUANXIAN  WCX', value: '武川县'},
		 {name: '包头  BAOTOU  BTS', value: '包头'},
		 {name: '赤峰  CHIFENG  CFS', value: '赤峰'},
		 {name: '鄂尔多斯  EERDUOSI', value: '鄂尔多斯'},
		 {name: '乌海  WUHAI  WHM', value: '乌海'},
		 {name: '通辽  TONGLIAO  TLO', value: '通辽'},
		 {name: '呼伦贝尔  HULUNBEIER  HBM', value: '呼伦贝尔'},
		 {name: '巴彦淖尔  BAYANNAOER', value: '巴彦淖尔'},
		 {name: '乌兰察布  WULANCHABU', value: '乌兰察布'},
		 {name: '兴安盟  XINGANMENG', value: '兴安盟'},
		 {name: '锡林郭勒盟  XILINGUOLEMENG  XGO', value: '锡林郭勒盟'},
		 {name: '阿拉善盟  ALASHANMENG  ALM', value: '阿拉善盟'},
		 {name: '乌审旗  WUSHENQI  UXI', value: '乌审旗'},
		 {name: '满洲里  MANZHOULI  MLX', value: '满洲里'},
		 {name: '宁夏  NINGXIA  NX', value: '宁夏'},
		 {name: '银川  YINCHUAN  INC', value: '银川'},
		 {name: '西夏区  XIXIAQU', value: '西夏区'},
		 {name: '金凤区  JINFENGQU', value: '金凤区'},
		 {name: '兴庆区  XINGQINGQU', value: '兴庆区'},
		 {name: '灵武市  LINGWUSHI  LWU', value: '灵武市'},
		 {name: '永宁县  YONGNINGXIAN  YGN', value: '永宁县'},
		 {name: '贺兰县  HELANXIAN  HLN', value: '贺兰县'},
		 {name: '中卫  ZHONGWEI  ZWE', value: '中卫'},
		 {name: '石嘴山  SHIZUISHAN', value: '石嘴山'},
		 {name: '吴忠  WUZHONG  WZS', value: '吴忠'},
		 {name: '青铜峡  QINGTONGXIA  QTX', value: '青铜峡'},
		 {name: '石嘴山  SHIZUISHAN', value: '石嘴山'},
		 {name: '吴忠  WUZHONG  WZS', value: '吴忠'},
		 {name: '固原  GUYUAN', value: '固原'},
		 {name: '中卫  ZHONGWEI  ZWE', value: '中卫'},
		 {name: '青海省  QINGHAI  QH', value: '青海省'},
		 {name: '西宁  XINING  XNN', value: '西宁'},
		 {name: '城中区  CHENGZHONGQU  CZQ', value: '城中区'},
		 {name: '城东区  CHENGDONGQU  CDQ', value: '城东区'},
		 {name: '城西区  CHENGXIQU  CXQ', value: '城西区'},
		 {name: '城北区  CHENGBEIQU  CBE', value: '城北区'},
		 {name: '湟中县  HUANGZHONGXIAN  HZX', value: '湟中县'},
		 {name: '湟源县  HUANGYUANXIAN  HYU', value: '湟源县'},
		 {name: '大通  DATONG', value: '大通'},
		 {name: '城南区  CHENGNANXINQU  CNN', value: '城南区'},
		 {name: '海湖区  HAIHUXINQU', value: '海湖区'},
		 {name: '海东  HAIDONG  HDD', value: '海东'},
		 {name: '海西  HAIXI  HXZ', value: '海西'},
		 {name: '海北  HAIBEI  HBZ', value: '海北'},
		 {name: '黄南  HUANGNAN  HNZ', value: '黄南'},
		 {name: '海南  HAINAN', value: '海南'},
		 {name: '果洛  GUOLUO  GOL', value: '果洛'},
		 {name: '玉树  YUSHU', value: '玉树'},
		 {name: '山东省  SHANDONG  SD', value: '山东省'},
		 {name: '济南  JINAN  JNA', value: '济南'},
		 {name: '市中区  SHIZHONGQU  SZP', value: '市中区'},
		 {name: '历下区  LIXIAQU  LXQ', value: '历下区'},
		 {name: '天桥区  TIANQIAOQU  TQQ', value: '天桥区'},
		 {name: '槐荫区  HUAIYINQU  HYF', value: '槐荫区'},
		 {name: '历城区  LICHENGQU  LCZ', value: '历城区'},
		 {name: '长清区  CHANGQINGQU  CQG', value: '长清区'},
		 {name: '章丘市  ZHANGQIUSHI  ZQS', value: '章丘市'},
		 {name: '平阴县  PINGYINXIAN  PYL', value: '平阴县'},
		 {name: '济阳县  JIYANGXIAN  JYL', value: '济阳县'},
		 {name: '商河县  SHANGHEXIAN  SGH', value: '商河县'},
		 {name: '高新区  GAOXINQU', value: '高新区'},
		 {name: '近郊  JINJIAO', value: '近郊'},
		 {name: '德州  DEZHOU  DZS', value: '德州'},
		 {name: '东营  DONGYING', value: '东营'},
		 {name: '济宁  JINING  JNG', value: '济宁'},
		 {name: '临沂  LINYI  LYI', value: '临沂'},
		 {name: '青岛  QINGDAO  TAO', value: '青岛'},
		 {name: '市南区  SHINANQU  SNQ', value: '市南区'},
		 {name: '市北区  SHIBEIQU  SBQ', value: '市北区'},
		 {name: '城阳区  CHENGYANGQU  CEY', value: '城阳区'},
		 {name: '四方区  SIFANGQU', value: '四方区'},
		 {name: '李沧区  LICANGQU  LCT', value: '李沧区'},
		 {name: '黄岛区  HUANGDAOQU  HDO', value: '黄岛区'},
		 {name: '崂山区  LAOSHANQU  LQD', value: '崂山区'},
		 {name: '胶州市  JIAOZHOUSHI  JZS', value: '胶州市'},
		 {name: '即墨市  JIMOSHI  JMO', value: '即墨市'},
		 {name: '平度市  PINGDUSHI  PDU', value: '平度市'},
		 {name: '胶南市  JIAONANSHI  JNS', value: '胶南市'},
		 {name: '莱西市  LAIXISHI  LXE', value: '莱西市'},
		 {name: '日照  RIZHAO  RZH', value: '日照'},
		 {name: '泰安  TAIAN  TAI', value: '泰安'},
		 {name: '威海  WEIHAI  WEH', value: '威海'},
		 {name: '潍坊  WEIFANG  WEF', value: '潍坊'},
		 {name: '烟台  YANTAI  YNT', value: '烟台'},
		 {name: '淄博  ZIBO  ZBO', value: '淄博'},
		 {name: '枣庄  ZAOZHUANG  ZZG', value: '枣庄'},
		 {name: '滨州  BINZHOU', value: '滨州'},
		 {name: '聊城  LIAOCHENG  LCH', value: '聊城'},
		 {name: '菏泽  HEZE  HZS', value: '菏泽'},
		 {name: '莱芜  LAIWU  LWS', value: '莱芜'},
		 {name: '荣成  RONGCHENG', value: '荣成'},
		 {name: '黄岛  HUANGDAO  HDO', value: '黄岛'},
		 {name: '乳山  RUSHAN  RSN', value: '乳山'},
		 {name: '城阳  CHENGYANG  CEY', value: '城阳'},
		 {name: '即墨  JIMO  JMO', value: '即墨'},
		 {name: '肥城  FEICHENG  FEC', value: '肥城'},
		 {name: '兖州  YANZHOU  YZL', value: '兖州'},
		 {name: '海阳  HAIYANG  HYL', value: '海阳'},
		 {name: '胶州  JIAOZHOU  JZS', value: '胶州'},
		 {name: '胶南  JIAONAN  JNS', value: '胶南'},
		 {name: '平度  PINGDU  PDU', value: '平度'},
		 {name: '莱西  LAIXI  LXE', value: '莱西'},
		 {name: '山西省  SHANXI  SX', value: '山西省'},
		 {name: '太原  TAIYUAN  TYN', value: '太原'},
		 {name: '杏花岭  XINGHUALINGQU  XHL', value: '杏花岭'},
		 {name: '小店区  XIAODIANQU  XDQ', value: '小店区'},
		 {name: '迎泽区  YINGZEQU  YZT', value: '迎泽区'},
		 {name: '尖草坪  JIANCAOPINGQU  JCP', value: '尖草坪'},
		 {name: '万柏林  WANBAILINQU  WBL', value: '万柏林'},
		 {name: '晋源区  JINYUANQU  JYM', value: '晋源区'},
		 {name: '高新区  GAOXINQU', value: '高新区'},
		 {name: '开发区  JINGJIKAIFAQU', value: '开发区'},
		 {name: '工业园  GONGYEYUANQU', value: '工业园'},
		 {name: '清徐县  QINGXUXIAN  QXU', value: '清徐县'},
		 {name: '阳曲县  YANGQUXIAN  YGQ', value: '阳曲县'},
		 {name: '娄烦县  LOUFANXIAN  LFA', value: '娄烦县'},
		 {name: '古交市  GUJIAOSHI  GUJ', value: '古交市'},
		 {name: '大同  DATONG', value: '大同'},
		 {name: '临汾  LINFEN', value: '临汾'},
		 {name: '运城  YUNCHENG', value: '运城'},
		 {name: '长治  CHANGZHI', value: '长治'},
		 {name: '阳泉  YANGQUAN  YQS', value: '阳泉'},
		 {name: '晋城  JINCHENG  JCG', value: '晋城'},
		 {name: '朔州  SHUOZHOU  SZJ', value: '朔州'},
		 {name: '晋中  JINZHONG  JZD', value: '晋中'},
		 {name: '忻州  XINZHOU', value: '忻州'},
		 {name: '吕梁  LVLIANG  LLD', value: '吕梁'},
		 {name: '永济  YONGJI  YJJ', value: '永济'},
		 {name: '和顺  HESHUN  HSJ', value: '和顺'},
		 {name: '陕西省  SHANXI  SN', value: '陕西省'},
		 {name: '西安  XIAN', value: '西安'},
		 {name: '宝鸡  BAOJI', value: '宝鸡'},
		 {name: '咸阳  XIANYANG  XYS', value: '咸阳'},
		 {name: '铜川  TONGCHUAN  TCN', value: '铜川'},
		 {name: '渭南  WEINAN  WNA', value: '渭南'},
		 {name: '汉中  HANZHONG  HZJ', value: '汉中'},
		 {name: '安康  ANKANG', value: '安康'},
		 {name: '商洛  SHANGLUO  SLD', value: '商洛'},
		 {name: '延安  YANAN  YNA', value: '延安'},
		 {name: '榆林  YU_LIN', value: '榆林  YU_'},
		 {name: '杨凌  YANGLING', value: '杨凌'},
		 {name: '兴平  XINGPING  XPG', value: '兴平'},
		 {name: '四川省  SICHUAN  SC', value: '四川省'},
		 {name: '成都  CHENGDU  CTU', value: '成都'},
		 {name: '成华区  CHENGHUA  CHQ', value: '成华区'},
		 {name: '武侯区  WUHOU  WHQ', value: '武侯区'},
		 {name: '青羊区  QINGYANG  QYQ', value: '青羊区'},
		 {name: '锦江区  JINJIANG  JJQ', value: '锦江区'},
		 {name: '金牛区  JINNIU  JNU', value: '金牛区'},
		 {name: '龙泉驿  LONGQUANYI', value: '龙泉驿'},
		 {name: '青白江  QINGBAIJIANG  QBJ', value: '青白江'},
		 {name: '新都区  XINDU  XDU', value: '新都区'},
		 {name: '双流县  SHUANGLIU  SLU', value: '双流县'},
		 {name: '郫县  PIXIAN  PIX', value: '郫县'},
		 {name: '温江区  WENJIANG  WNJ', value: '温江区'},
		 {name: '大邑县  DAYI  DYI', value: '大邑县'},
		 {name: '金堂县  JINTANG  JNT', value: '金堂县'},
		 {name: '蒲江县  PUJIANG  PJX', value: '蒲江县'},
		 {name: '新津县  XINJIN  XJC', value: '新津县'},
		 {name: '温江区  WENJIANGQU  WNJ', value: '温江区'},
		 {name: '高新区  GAOXINQU', value: '高新区'},
		 {name: '高新西  GAOXINXIQU', value: '高新西'},
		 {name: '都江堰  DOUJIANGYANSHI  DJY', value: '都江堰'},
		 {name: '彭州市  PENGZHOUSHI  PZS', value: '彭州市'},
		 {name: '邛崃市  QIONGLAISHI  QLA', value: '邛崃市'},
		 {name: '崇州市  CHONGZHOUSHI  CZO', value: '崇州市'},
		 {name: '乐山  LESHAN  LES', value: '乐山'},
		 {name: '泸州  LUZHOU  LUZ', value: '泸州'},
		 {name: '绵阳  MIANYANG  MYG', value: '绵阳'},
		 {name: '内江  NEIJIANG  NJS', value: '内江'},
		 {name: '宜宾  YIBIN', value: '宜宾'},
		 {name: '自贡  ZIGONG  ZGS', value: '自贡'},
		 {name: '攀枝花  PANZHIHUA  PZH', value: '攀枝花'},
		 {name: '德阳  DEYANG  DEY', value: '德阳'},
		 {name: '广元  GUANGYUAN  GYC', value: '广元'},
		 {name: '遂宁  SUINING  SNS', value: '遂宁'},
		 {name: '南充  NANCHONG  NCO', value: '南充'},
		 {name: '眉山  MEISHAN', value: '眉山'},
		 {name: '广安  GUANGAN', value: '广安'},
		 {name: '达州  DAZHOU', value: '达州'},
		 {name: '雅安  YAAN', value: '雅安'},
		 {name: '巴中  BAZHONG', value: '巴中'},
		 {name: '资阳  ZIYANG', value: '资阳'},
		 {name: '西昌  XICHANG  XCA', value: '西昌'},
		 {name: '甘孜  GANZI', value: '甘孜'},
		 {name: '阿坝  ABEI', value: '阿坝'},
		 {name: '凉山  LIANGSHAN  LSY', value: '凉山'},
		 {name: '峨眉  EMEI  EMS', value: '峨眉'},
		 {name: '简阳  JIANYANG  JYC', value: '简阳'},
		 {name: '西藏  XIZANG  XZ', value: '西藏'},
		 {name: '拉萨  LASA  LXA', value: '拉萨'},
		 {name: '城关区  CHENGGUANQU  CLZ', value: '城关区'},
		 {name: '林周县  LINZHOUXIAN  LZB', value: '林周县'},
		 {name: '当雄县  DANGXIONGXIAN  DAM', value: '当雄县'},
		 {name: '尼木县  NIMUXIAN  NYE', value: '尼木县'},
		 {name: '曲水县  QUSHUIXIAN  QUX', value: '曲水县'},
		 {name: '龙德庆  DUILONGDEQINGXIAN', value: '龙德庆'},
		 {name: '达孜县  DAZIXIAN  DAG', value: '达孜县'},
		 {name: '工卡县  MOZHUGONGKAXIAN', value: '工卡县'},
		 {name: '日喀则  RIKAZE', value: '日喀则'},
		 {name: '林芝  LINZHI', value: '林芝'},
		 {name: '山南  SHANNAN  SND', value: '山南'},
		 {name: '昌都  CHANGDU', value: '昌都'},
		 {name: '那曲  NAQU', value: '那曲'},
		 {name: '阿里  ALI  NGD', value: '阿里'},
		 {name: '新疆  XINJIANG  XJ', value: '新疆'},
		 {name: '乌鲁木齐  WULUMUQI', value: '乌鲁木齐'},
		 {name: '天山区  TIANSHANQU  TSL', value: '天山区'},
		 {name: '巴克区  SHAYIBAKEQU', value: '巴克区'},
		 {name: '新市区  XINSHIQU  XSU', value: '新市区'},
		 {name: '水磨沟  SHUIMOGOUQU  SMG', value: '水磨沟'},
		 {name: '头屯河  TOUTUNHEQU  TTH', value: '头屯河'},
		 {name: '达坂城  DABANCHENGQU', value: '达坂城'},
		 {name: '米东区  MIDONGQU', value: '米东区'},
		 {name: '乌县  WULUMUQIXIAN', value: '乌县'},
		 {name: '昌吉市  CHANGJISHI', value: '昌吉市'},
		 {name: '五家渠  WUJIAQUSHI', value: '五家渠'},
		 {name: '阜康市  FUKANGSHI  FKG', value: '阜康市'},
		 {name: '喀什  KASHI', value: '喀什'},
		 {name: '克拉玛依  KELAMAYI', value: '克拉玛依'},
		 {name: '伊犁  YILI', value: '伊犁'},
		 {name: '阿克苏  AKESU', value: '阿克苏'},
		 {name: '哈密  HAMI', value: '哈密'},
		 {name: '石河子  SHIHEZI  SHZ', value: '石河子'},
		 {name: '阿拉尔  ALAER', value: '阿拉尔'},
		 {name: '五家渠  WUJIAQU', value: '五家渠'},
		 {name: '图木舒克  TUMUSHUKE', value: '图木舒克'},
		 {name: '昌吉  CHANGJI', value: '昌吉'},
		 {name: '阿勒泰  ALETAI', value: '阿勒泰'},
		 {name: '吐鲁番  TULUFAN', value: '吐鲁番'},
		 {name: '塔城  TACHENG', value: '塔城'},
		 {name: '和田  HETIAN', value: '和田'},
		 {name: '巴音郭楞  BAYINGUOLENG  BAG', value: '巴音郭楞'},
		 {name: '博尔塔拉  BOERTALA  BOR', value: '博尔塔拉'},
		 {name: '奎屯市  KUITUNSHI  KUY', value: '奎屯市'},
		 {name: '乌苏  WUSU  USU', value: '乌苏'},
		 {name: '克州  KEZILESUKEERKEZI', value: '克州'},
		 {name: '云南省  YUNNAN  YN', value: '云南省'},
		 {name: '昆明  KUNMING  KMG', value: '昆明'},
		 {name: '盘龙区  PANLONGQU  PLQ', value: '盘龙区'},
		 {name: '五华区  WUHUAQU', value: '五华区'},
		 {name: '官渡区  GUANDUQU  GDU', value: '官渡区'},
		 {name: '西山区  XISHANQU  XSN', value: '西山区'},
		 {name: '东川区  DONGCHUANQU  DCU', value: '东川区'},
		 {name: '安宁市  ANNINGSHI', value: '安宁市'},
		 {name: '呈贡新  CHENGGONGXINQU  CGD', value: '呈贡新'},
		 {name: '晋宁新  JINNINGXINQU  JND', value: '晋宁新'},
		 {name: '富民区  FUMINQU  FMN', value: '富民区'},
		 {name: '宜良区  YILIANGQU  YIL', value: '宜良区'},
		 {name: '嵩明区  SONGMINGQU  SMI', value: '嵩明区'},
		 {name: '石林县  SHILINXIAN  SLY', value: '石林县'},
		 {name: '禄劝  LUQUAN  LUC', value: '禄劝'},
		 {name: '寻甸  XUNDIAN  XDN', value: '寻甸'},
		 {name: '大理  DALI', value: '大理'},
		 {name: '丽江  LIJIANG', value: '丽江'},
		 {name: '玉溪  YUXI  YXS', value: '玉溪'},
		 {name: '曲靖  QUJING  QJS', value: '曲靖'},
		 {name: '保山  BAOSHAN', value: '保山'},
		 {name: '昭通  ZHAOTONG', value: '昭通'},
		 {name: '普洱  PUER  PER', value: '普洱'},
		 {name: '临沧  LINCANG', value: '临沧'},
		 {name: '红河  HONGHE', value: '红河'},
		 {name: '文山  WENSHAN', value: '文山'},
		 {name: '西双版纳  XISHUANGBANNA  XSB', value: '西双版纳'},
		 {name: '德宏  DEHONG  DHG', value: '德宏'},
		 {name: '楚雄  CHUXIONG', value: '楚雄'},
		 {name: '怒江  NUJIANG  NUJ', value: '怒江'},
		 {name: '迪庆  DIQING  DEZ', value: '迪庆'},
		 {name: '思茅  SIMAO', value: '思茅'},
		 {name: '香港  HONGKONG  HK', value: '香港'},
		 {name: '沙田区  SHATIANQU', value: '沙田区'},
		 {name: '东区  DONGQU  DQP', value: '东区'},
		 {name: '观塘区  GUANTANGQU', value: '观塘区'},
		 {name: '黄大仙  HUANGDAXIANQU', value: '黄大仙'},
		 {name: '九龙城  JIULONGCHENGQU  JLC', value: '九龙城'},
		 {name: '屯门区  TUNMENQU', value: '屯门区'},
		 {name: '葵青区  KUIQINGQU', value: '葵青区'},
		 {name: '元朗区  YUANLANGQU', value: '元朗区'},
		 {name: '深水埗  SHENSHUIBUQU', value: '深水埗'},
		 {name: '西贡区  XIGONGQU', value: '西贡区'},
		 {name: '大埔区  DAPUQU  DBX', value: '大埔区'},
		 {name: '湾仔区  WANZIQU', value: '湾仔区'},
		 {name: '油尖旺  YOUJIANWANGQU', value: '油尖旺'},
		 {name: '北区  BEIQU', value: '北区'},
		 {name: '南区  NANQU', value: '南区'},
		 {name: '荃湾区  QUANWANQU', value: '荃湾区'},
		 {name: '中西区  ZHONGXIQU', value: '中西区'},
		 {name: '离岛区  LIDAOQU', value: '离岛区'},
		 {name: '澳门  MACAO', value: '澳门'},
		 {name: '台湾  TAIWAN  TW', value: '台湾'},
		 {name: '台北  TAIBEI', value: '台北'},
		 {name: '高雄  GAOXIONG', value: '高雄'},
		 {name: '基隆  JILONG', value: '基隆'},
		 {name: '台中  TAIZHONG', value: '台中'},
		 {name: '台南  TAINAN', value: '台南'},
		 {name: '新竹  XINZHU', value: '新竹'},
		 {name: '嘉义  JIAYI', value: '嘉义'},
		 {name: '宜兰县  YILANXIAN', value: '宜兰县'},
		 {name: '桃园县  TAOYUANXIAN', value: '桃园县'},
		 {name: '苗栗县  MIAOLIXIAN', value: '苗栗县'},
		 {name: '彰化县  ZHANGHUAXIAN', value: '彰化县'},
		 {name: '南投县  NANTOUXIAN', value: '南投县'},
		 {name: '云林县  YUNLINXIAN', value: '云林县'},
		 {name: '屏东县  PINGDONGXIAN', value: '屏东县'},
		 {name: '台东县  TAIDONGXIAN', value: '台东县'},
		 {name: '花莲县  HUALIANXIAN', value: '花莲县'},
		 {name: '澎湖县  PENGHUXIAN', value: '澎湖县'},
		 {name: '亚洲  Asia', value: '亚洲'},
		 {name: '蒙古  Mongolia', value: '蒙古'},
		 {name: '朝鲜  North Korea', value: '朝鲜'},
		 {name: '韩国  Korea', value: '韩国'},
		 {name: '日本  Japan', value: '日本'},
		 {name: '菲律宾  Philippines', value: '菲律宾'},
		 {name: '越南  Vietnam', value: '越南'},
		 {name: '老挝  Laos', value: '老挝'},
		 {name: '柬埔寨  Cambodia', value: '柬埔寨'},
		 {name: '缅甸  Burma', value: '缅甸'},
		 {name: '泰国  Thailand', value: '泰国'},
		 {name: '马来西亚  Malaysia', value: '马来西亚'},
		 {name: '文莱  Brunei', value: '文莱'},
		 {name: '新加坡  Singapore', value: '新加坡'},
		 {name: '印度尼西亚  Indonesia', value: '印度尼西亚'},
		 {name: '东帝汶  east Timor', value: '东帝汶'},
		 {name: '尼泊尔  Nepal', value: '尼泊尔'},
		 {name: '不丹  Bhutan', value: '不丹'},
		 {name: '孟加拉  Bangladesh', value: '孟加拉'},
		 {name: '印度  India', value: '印度'},
		 {name: '巴基斯坦  Pakistan', value: '巴基斯坦'},
		 {name: '斯里兰卡  Sri Lanka', value: '斯里兰卡'},
		 {name: '马尔代夫  Maldives', value: '马尔代夫'},
		 {name: '哈萨克斯坦  Kazakhstan', value: '哈萨克斯坦'},
		 {name: '吉尔吉斯  Kyrghyzstan', value: '吉尔吉斯'},
		 {name: '塔吉克斯坦  Tajikistan', value: '塔吉克斯坦'},
		 {name: '乌兹别克  Uzbekistan', value: '乌兹别克'},
		 {name: '土库曼斯坦  Turkmenistan', value: '土库曼斯坦'},
		 {name: '阿富汗  Afghanistan', value: '阿富汗'},
		 {name: '伊拉克  Iraq', value: '伊拉克'},
		 {name: '伊朗  Iran', value: '伊朗'},
		 {name: '叙利亚  Syria', value: '叙利亚'},
		 {name: '约旦  Jordan', value: '约旦'},
		 {name: '黎巴嫩  Lebanon', value: '黎巴嫩'},
		 {name: '以色列  Israel', value: '以色列'},
		 {name: '巴勒斯坦  Palestine', value: '巴勒斯坦'},
		 {name: '沙特阿拉伯  Saudi Arabia', value: '沙特阿拉伯'},
		 {name: '巴林  Bahrain', value: '巴林'},
		 {name: '卡塔尔  Qatar', value: '卡塔尔'},
		 {name: '科威特  Kuwait', value: '科威特'},
		 {name: '阿联酋  United Arab Emirates', value: '阿联酋'},
		 {name: '阿曼  Oman', value: '阿曼'},
		 {name: '也门  Yemen', value: '也门'},
		 {name: '格鲁吉亚  Georgia', value: '格鲁吉亚'},
		 {name: '亚美尼亚  Armenia', value: '亚美尼亚'},
		 {name: '阿塞拜疆  Azerbaijan', value: '阿塞拜疆'},
		 {name: '土耳其  Turkey', value: '土耳其'},
		 {name: '塞浦路斯  Cyprus', value: '塞浦路斯'},
		 {name: '北美洲  North America', value: '北美洲'},
		 {name: '加拿大  Canada', value: '加拿大'},
		 {name: '阿尔伯塔省  Alberta', value: '阿尔伯塔省'},
		 {name: '卡尔加里  Calgary', value: '卡尔加里'},
		 {name: '埃德蒙顿  Edmonton', value: '埃德蒙顿'},
		 {name: '不列颠哥伦比亚省  British Columbia', value: '不列颠哥伦比亚省'},
		 {name: '温哥华  Vancouver', value: '温哥华'},
		 {name: '素里  Surrey', value: '素里'},
		 {name: '本拿比  Burnaby', value: '本拿比'},
		 {name: '列治文  Richmond', value: '列治文'},
		 {name: '曼尼托巴省  Manitoba', value: '曼尼托巴省'},
		 {name: '温尼伯  Winnipeg', value: '温尼伯'},
		 {name: '纽芬兰与拉布拉多省  Newfoundland and Labrador', value: '纽芬兰与拉布拉多省'},
		 {name: '新不伦瑞克省  New Brunswick', value: '新不伦瑞克省'},
		 {name: '新斯科舍省  Nova Scotia', value: '新斯科舍省'},
		 {name: '哈利法克斯  Halifax', value: '哈利法克斯'},
		 {name: '安大略省  Ontario', value: '安大略省'},
		 {name: '多伦多  Toronto  DLM', value: '多伦多'},
		 {name: '渥太华  Ottawa', value: '渥太华'},
		 {name: '密西沙加  Mississauga', value: '密西沙加'},
		 {name: '宾顿  Brampton', value: '宾顿'},
		 {name: '汉密尔顿  Hamilton', value: '汉密尔顿'},
		 {name: '伦敦  London', value: '伦敦'},
		 {name: '万锦  Markham', value: '万锦'},
		 {name: '旺市  Vaughan', value: '旺市'},
		 {name: '基奇纳  Kitchener', value: '基奇纳'},
		 {name: '温莎  Windsor', value: '温莎'},
		 {name: '列治文山  Richmond Hill', value: '列治文山'},
		 {name: '奥克维尔  Okville', value: '奥克维尔'},
		 {name: '伯灵顿  Burlington', value: '伯灵顿'},
		 {name: '萨德伯里  Greater Sudbury', value: '萨德伯里'},
		 {name: '爱德华王子岛省  Prince Edward Island', value: '爱德华王子岛省'},
		 {name: '魁北克省  Quebec', value: '魁北克省'},
		 {name: '蒙特利尔  Montreal', value: '蒙特利尔'},
		 {name: '魁北克城  Quebec City', value: '魁北克城'},
		 {name: '拉瓦尔  Laval', value: '拉瓦尔'},
		 {name: '加蒂诺  Gatineau', value: '加蒂诺'},
		 {name: '朗基尔  Longueuil', value: '朗基尔'},
		 {name: '舍布鲁克  Sherbrooke', value: '舍布鲁克'},
		 {name: '萨斯喀彻温省  Saskatchewan', value: '萨斯喀彻温省'},
		 {name: '萨斯卡通  Saskatoon', value: '萨斯卡通'},
		 {name: '里贾纳  Regina', value: '里贾纳'},
		 {name: '努纳武特地区  Nunavut', value: '努纳武特地区'},
		 {name: '西北地区  Northwest Territories', value: '西北地区'},
		 {name: '育空地区  Yukon', value: '育空地区'},
		 {name: '美国  America', value: '美国'},
		 {name: '亚拉巴马州  Alabama', value: '亚拉巴马州'},
		 {name: '伯明翰  Birmingham', value: '伯明翰'},
		 {name: '蒙哥马利  Montgomery', value: '蒙哥马利'},
		 {name: '亨次维尔  Huntsville', value: '亨次维尔'},
		 {name: '塔斯卡卢萨  Tuscaloosa', value: '塔斯卡卢萨'},
		 {name: '莫比尔港  Mobile', value: '莫比尔港'},
		 {name: '阿拉斯加州  Alaska', value: '阿拉斯加州'},
		 {name: '朱诺  Juneau', value: '朱诺'},
		 {name: '安克拉奇  Anchorage', value: '安克拉奇'},
		 {name: '亚利桑那州  Arizona', value: '亚利桑那州'},
		 {name: '菲尼克斯 凤凰城   Phoenix', value: '菲尼克斯 凤凰城'},
		 {name: '图森  Tucson', value: '图森'},
		 {name: '阿肯色州  Arkansas', value: '阿肯色州'},
		 {name: '小石城  Little Rock', value: '小石城'},
		 {name: '加利福尼亚州  California', value: '加利福尼亚州'},
		 {name: '萨克拉门托  Sacramento', value: '萨克拉门托'},
		 {name: '索诺马  Sonoma', value: '索诺马'},
		 {name: '圣荷西  San Jose', value: '圣荷西'},
		 {name: '洛杉矶  Los Angeles', value: '洛杉矶'},
		 {name: '圣地亚哥  San Diego', value: '圣地亚哥'},
		 {name: '科罗拉多州  Colorado', value: '科罗拉多州'},
		 {name: '丹佛  Denver', value: '丹佛'},
		 {name: '波尔德  Boulder', value: '波尔德'},
		 {name: '康涅狄格州  Connecticut', value: '康涅狄格州'},
		 {name: '特拉华州  Delaware', value: '特拉华州'},
		 {name: '多佛  Dover', value: '多佛'},
		 {name: '维明顿  Wilmington', value: '维明顿'},
		 {name: '纽华克  Newark', value: '纽华克'},
		 {name: '佛罗里达州  Florida', value: '佛罗里达州'},
		 {name: '塔拉赫西  Tallahassee', value: '塔拉赫西'},
		 {name: '坦帕  Tampa', value: '坦帕'},
		 {name: '杰克逊维尔  Jacksonville', value: '杰克逊维尔'},
		 {name: '迈阿密  Miami', value: '迈阿密'},
		 {name: '乔治亚州  Georgia', value: '乔治亚州'},
		 {name: '亚特兰大  Atlanta', value: '亚特兰大'},
		 {name: '哥伦布  Columbus', value: '哥伦布'},
		 {name: '夏威夷州  Hawaii', value: '夏威夷州'},
		 {name: '爱达荷州  Boise', value: '爱达荷州'},
		 {name: '波夕  Atlanta', value: '波夕'},
		 {name: '波卡特洛  Pocatello', value: '波卡特洛'},
		 {name: '伊利诺伊州  Illinois', value: '伊利诺伊州'},
		 {name: '春田  Springfield', value: '春田'},
		 {name: '芝加哥  Chicago', value: '芝加哥'},
		 {name: '印第安那州  Indiana', value: '印第安那州'},
		 {name: '印第安纳波利斯  Indianapolis', value: '印第安纳波利斯'},
		 {name: '韦恩堡  Fort Wayne', value: '韦恩堡'},
		 {name: '伯明顿  Bloomington', value: '伯明顿'},
		 {name: '爱荷华州  Iowa', value: '爱荷华州'},
		 {name: '得梅因  Des Moines', value: '得梅因'},
		 {name: '锡达拉皮兹  Cedar Rapids', value: '锡达拉皮兹'},
		 {name: '丹芬堡特  Daven Port', value: '丹芬堡特'},
		 {name: '堪萨斯州  Kansas', value: '堪萨斯州'},
		 {name: '托皮卡  Topeka', value: '托皮卡'},
		 {name: '威奇托  Wichita', value: '威奇托'},
		 {name: '堪萨斯城  Kansas City', value: '堪萨斯城'},
		 {name: '肯塔基州  Kentucky', value: '肯塔基州'},
		 {name: '路易斯维尔  Louisville', value: '路易斯维尔'},
		 {name: '列克星敦  Lexington', value: '列克星敦'},
		 {name: '路易斯安那州  Louisiana', value: '路易斯安那州'},
		 {name: '新奥尔良  New Orleans', value: '新奥尔良'},
		 {name: '缅因州  Maine', value: '缅因州'},
		 {name: '奥古斯塔  Augusta', value: '奥古斯塔'},
		 {name: '马里兰州  Maryland', value: '马里兰州'},
		 {name: '安纳波利斯  Annapolis', value: '安纳波利斯'},
		 {name: '巴尔的摩  Baltimore', value: '巴尔的摩'},
		 {name: '麻萨诸塞州  Massachusetts', value: '麻萨诸塞州'},
		 {name: '波士顿  Boston', value: '波士顿'},
		 {name: '密歇根州  Michigan', value: '密歇根州'},
		 {name: '兰辛  Lansing', value: '兰辛'},
		 {name: '底特律  Detroit', value: '底特律'},
		 {name: '大溪城  Grand Rapids', value: '大溪城'},
		 {name: '明尼苏达州  Minnesota', value: '明尼苏达州'},
		 {name: '圣保罗  Saint Paul', value: '圣保罗'},
		 {name: '明尼阿波利斯  Minneapolis', value: '明尼阿波利斯'},
		 {name: '密西西比州  Mississippi', value: '密西西比州'},
		 {name: '杰克逊  Jackson', value: '杰克逊'},
		 {name: '密苏里州  Missouri', value: '密苏里州'},
		 {name: '杰佛逊城  Jefferson City', value: '杰佛逊城'},
		 {name: '圣路易斯  Saint Louis', value: '圣路易斯'},
		 {name: '堪萨斯城  Kansas City', value: '堪萨斯城'},
		 {name: '洛拉  Rolla', value: '洛拉'},
		 {name: '蒙大拿州  Montana', value: '蒙大拿州'},
		 {name: '海伦娜  Heldna  HLU', value: '海伦娜'},
		 {name: '比林斯  Billings', value: '比林斯'},
		 {name: '密苏拉  Missoula', value: '密苏拉'},
		 {name: '内布拉斯加州  Nebraska', value: '内布拉斯加州'},
		 {name: '林肯  Lincoln', value: '林肯'},
		 {name: '内华达州  Nevada', value: '内华达州'},
		 {name: '卡森城  Carson City', value: '卡森城'},
		 {name: '拉斯维加斯  Las Vegas', value: '拉斯维加斯'},
		 {name: '里诺  Reno', value: '里诺'},
		 {name: '新罕布什尔州  New Hampshire', value: '新罕布什尔州'},
		 {name: '曼彻斯特  Manchester', value: '曼彻斯特'},
		 {name: '南雪  Nashua', value: '南雪'},
		 {name: '朴次茅斯  Portsmouth', value: '朴次茅斯'},
		 {name: '新泽西州  New Jersey', value: '新泽西州'},
		 {name: '纽瓦克  Newark', value: '纽瓦克'},
		 {name: '泽西市  Jersey City', value: '泽西市'},
		 {name: '大西洋城  Atlantic City', value: '大西洋城'},
		 {name: '依丽沙白  Elizabeth', value: '依丽沙白'},
		 {name: '新墨西哥州  New Mexico', value: '新墨西哥州'},
		 {name: '圣达菲  Santa Fe', value: '圣达菲'},
		 {name: '阿尔布开克  Albuquerque', value: '阿尔布开克'},
		 {name: '纽约州  New York', value: '纽约州'},
		 {name: '奥尔巴尼 水牛城   Albany', value: '奥尔巴尼 水牛城'},
		 {name: '布法罗  Buffalo', value: '布法罗'},
		 {name: '长岛  Long Island  CDO', value: '长岛'},
		 {name: '纽约  New York City', value: '纽约'},
		 {name: '罗彻斯特市  Rochester', value: '罗彻斯特市'},
		 {name: '绮色佳  Ithaca', value: '绮色佳'},
		 {name: '北卡罗莱纳州  North Carolina', value: '北卡罗莱纳州'},
		 {name: '洛利  Raleigh', value: '洛利'},
		 {name: '夏洛特  Charlotte', value: '夏洛特'},
		 {name: '格林斯堡  Greensboro', value: '格林斯堡'},
		 {name: '查伯山  Chapel Hill', value: '查伯山'},
		 {name: '阿什维尔  Asheville', value: '阿什维尔'},
		 {name: '北达科他州  North Dakota', value: '北达科他州'},
		 {name: '俾斯麦  Bismark', value: '俾斯麦'},
		 {name: '法戈  Fargo', value: '法戈'},
		 {name: '俄亥俄州  Ohio', value: '俄亥俄州'},
		 {name: '哥伦布  Columbus', value: '哥伦布'},
		 {name: '克利夫兰  Cleveland', value: '克利夫兰'},
		 {name: '辛辛那提  Cincinnati', value: '辛辛那提'},
		 {name: '俄克拉何马州  Oklahoma', value: '俄克拉何马州'},
		 {name: '俄克拉何马城  OklahomaCity', value: '俄克拉何马城'},
		 {name: '塔尔萨  Tulsa', value: '塔尔萨'},
		 {name: '劳顿  Lawton', value: '劳顿'},
		 {name: '诺曼城  Norman', value: '诺曼城'},
		 {name: '俄勒冈州  Oregon', value: '俄勒冈州'},
		 {name: '塞伦  Salem', value: '塞伦'},
		 {name: '波特兰  Portland', value: '波特兰'},
		 {name: '尤金  Eugene', value: '尤金'},
		 {name: '科瓦利  Corvallis', value: '科瓦利'},
		 {name: '宾夕法尼亚州  Pennsylvania', value: '宾夕法尼亚州'},
		 {name: '哈里斯堡  Harrisburg', value: '哈里斯堡'},
		 {name: '南卡罗来纳州  South Carolina', value: '南卡罗来纳州'},
		 {name: '哥伦比亚  Columbia', value: '哥伦比亚'},
		 {name: '查理斯敦  North Charleston', value: '查理斯敦'},
		 {name: '格林威尔  Greenville', value: '格林威尔'},
		 {name: '阿干  Aiken', value: '阿干'},
		 {name: '美特尔沙滨  Myrtle Beach', value: '美特尔沙滨'},
		 {name: '克伦孙  Clemson', value: '克伦孙'},
		 {name: '南达科他州  South Dakota', value: '南达科他州'},
		 {name: '苏瀑市  Sioux Falls', value: '苏瀑市'},
		 {name: '拉皮特城  Rapid City', value: '拉皮特城'},
		 {name: '田纳西州  Tennessee', value: '田纳西州'},
		 {name: '那什维尔  Nemphis', value: '那什维尔'},
		 {name: '孟斐斯  Memphis', value: '孟斐斯'},
		 {name: '诺克斯维尔  Knoxville', value: '诺克斯维尔'},
		 {name: '橡树岭  Oak Ridge', value: '橡树岭'},
		 {name: '德克萨斯州  Texas', value: '德克萨斯州'},
		 {name: '奧斯汀  Austin', value: '奧斯汀'},
		 {name: '休斯顿  Houston', value: '休斯顿'},
		 {name: '达拉斯  Dallas', value: '达拉斯'},
		 {name: '犹他州  Utah', value: '犹他州'},
		 {name: '盐湖城  Salt Lake City', value: '盐湖城'},
		 {name: '奥格登  Ogden', value: '奥格登'},
		 {name: '普罗沃  Provo', value: '普罗沃'},
		 {name: '佛蒙特州  Vermont', value: '佛蒙特州'},
		 {name: '拉特兰  Rutland', value: '拉特兰'},
		 {name: '弗吉尼亚州  Virginia', value: '弗吉尼亚州'},
		 {name: '里齐蒙得  Richmond', value: '里齐蒙得'},
		 {name: '诺福克  Norfolk', value: '诺福克'},
		 {name: '弗吉尼亚滩  Virginia Beach', value: '弗吉尼亚滩'},
		 {name: '华盛顿州  Washington', value: '华盛顿州'},
		 {name: '奥林匹亚  Olympia', value: '奥林匹亚'},
		 {name: '罗得岛州  Rhode Island', value: '罗得岛州'},
		 {name: '普洛威顿斯  Providence', value: '普洛威顿斯'},
		 {name: '纽波特  Newport', value: '纽波特'},
		 {name: '西佛吉尼亚州  West Virginia', value: '西佛吉尼亚州'},
		 {name: '查理斯敦  Charleston', value: '查理斯敦'},
		 {name: '亨丁顿  Huntington', value: '亨丁顿'},
		 {name: '摩根敦  Morgantown', value: '摩根敦'},
		 {name: '威斯康星州  Wisconsin', value: '威斯康星州'},
		 {name: '麦迪逊  Madison', value: '麦迪逊'},
		 {name: '密尔沃基  Milwaukee', value: '密尔沃基'},
		 {name: '拉辛  Racine', value: '拉辛'},
		 {name: '怀俄明州  Wyoming', value: '怀俄明州'},
		 {name: '夏延  Cheyenne', value: '夏延'},
		 {name: '卡斯柏  Casper', value: '卡斯柏'},
		 {name: '拉阿密  Laramie', value: '拉阿密'},
		 {name: '华盛顿哥伦比亚特区  Washington DC', value: '华盛顿哥伦比亚特区'},
		 {name: '墨西哥  Mexico', value: '墨西哥'},
		 {name: '格陵兰  Greenland', value: '格陵兰'},
		 {name: '危地马拉  Guatemala', value: '危地马拉'},
		 {name: '伯利兹  Belize', value: '伯利兹'},
		 {name: '萨尔瓦多  Salvador', value: '萨尔瓦多'},
		 {name: '洪都拉斯  Honduras', value: '洪都拉斯'},
		 {name: '尼加拉瓜  Nicaragua', value: '尼加拉瓜'},
		 {name: '哥斯达黎加  Costa Rica', value: '哥斯达黎加'},
		 {name: '巴拿马  Panama', value: '巴拿马'},
		 {name: '巴哈马  Bahamas', value: '巴哈马'},
		 {name: '古巴  Cuba', value: '古巴'},
		 {name: '牙买加  Jamaica', value: '牙买加'},
		 {name: '海地  Haiti', value: '海地'},
		 {name: '多米尼加  Dominican Republic', value: '多米尼加'},
		 {name: '安提瓜  Antigua and Barbuda', value: '安提瓜'},
		 {name: '圣基茨  St. Kitts and Nevis', value: '圣基茨  St.'},
		 {name: '多米尼克  Dominica', value: '多米尼克'},
		 {name: '圣卢西亚  Saint Lucia', value: '圣卢西亚'},
		 {name: '圣文森特  Saint Vincent and the Grenadines', value: '圣文森特'},
		 {name: '格林纳达  Grenada', value: '格林纳达'},
		 {name: '巴巴多斯  Barbados', value: '巴巴多斯'},
		 {name: '特立尼达  Trinidad and Tobago', value: '特立尼达'},
		 {name: '波多黎各  Puerto Rico', value: '波多黎各'},
		 {name: '英属维尔京  British Virgin Islands', value: '英属维尔京'},
		 {name: '美属维尔京  Virgin Islands', value: '美属维尔京'},
		 {name: '安圭拉  Anguilla', value: '安圭拉'},
		 {name: '蒙特塞拉特  Montserrat', value: '蒙特塞拉特'},
		 {name: '瓜德罗普  Guadeloupe', value: '瓜德罗普'},
		 {name: '马提尼克  martinique', value: '马提尼克'},
		 {name: '安的列斯  Nederlandse Antillen', value: '安的列斯'},
		 {name: '阿鲁巴  Aruba', value: '阿鲁巴'},
		 {name: '特克斯  The turks and caicos islands  TEK', value: '特克斯'},
		 {name: '开曼群岛  Cayman Islands', value: '开曼群岛'},
		 {name: '百慕大  Bermuda', value: '百慕大'},
		 {name: '南美洲  South America', value: '南美洲'},
		 {name: '哥伦比亚  Columbia', value: '哥伦比亚'},
		 {name: '委内瑞拉  Venezuela', value: '委内瑞拉'},
		 {name: '圭亚那  Guyana', value: '圭亚那'},
		 {name: '法属圭亚那  French Guiana', value: '法属圭亚那'},
		 {name: '苏里南  Surinam', value: '苏里南'},
		 {name: '厄瓜多尔  Ecuador', value: '厄瓜多尔'},
		 {name: '秘鲁  Peru', value: '秘鲁'},
		 {name: '玻利维亚  Bolivia', value: '玻利维亚'},
		 {name: '巴西  Brazil', value: '巴西'},
		 {name: '智利  Chile', value: '智利'},
		 {name: '阿根廷  Argentina', value: '阿根廷'},
		 {name: '乌拉圭  Uruguay', value: '乌拉圭'},
		 {name: '巴拉圭  Paraguay', value: '巴拉圭'},
		 {name: '大洋洲  Oceania', value: '大洋洲'},
		 {name: '澳大利亚  Australia', value: '澳大利亚'},
		 {name: '新西兰  New Zealand', value: '新西兰'},
		 {name: '巴布亚  Papua New Guinea', value: '巴布亚'},
		 {name: '所罗门群岛  Solomon Islands', value: '所罗门群岛'},
		 {name: '瓦努阿图  Vanuatu', value: '瓦努阿图'},
		 {name: '马绍尔群岛  Marshall Islands', value: '马绍尔群岛'},
		 {name: '帕劳群岛  Palau', value: '帕劳群岛'},
		 {name: '瑙鲁  Nauru', value: '瑙鲁'},
		 {name: '基里巴斯  Kiribati', value: '基里巴斯'},
		 {name: '图瓦卢  Tuvalu', value: '图瓦卢'},
		 {name: '萨摩亚  Samoa', value: '萨摩亚'},
		 {name: '斐济群岛  Fiji Islands', value: '斐济群岛'},
		 {name: '汤加  Tonga', value: '汤加'},
		 {name: '库克群岛  Cook Islands', value: '库克群岛'},
		 {name: '关岛  Guam', value: '关岛'},
		 {name: '波利尼西亚  Polynesia', value: '波利尼西亚'},
		 {name: '皮特凯恩岛  Pitcairn Island', value: '皮特凯恩岛'},
		 {name: '瓦利斯  Wallis and Futuna', value: '瓦利斯'},
		 {name: '纽埃  Niue', value: '纽埃'},
		 {name: '托克劳  Tokelau', value: '托克劳'},
		 {name: '美属萨摩亚  American Samoa', value: '美属萨摩亚'},
		 {name: '北马里亚纳  Northern Marianas', value: '北马里亚纳'},
		 {name: '密克罗尼西亚  Micronesia', value: '密克罗尼西亚'},
		 {name: '新喀里多尼亚  New Caledonia', value: '新喀里多尼亚'},
		 {name: '欧洲  Europe', value: '欧洲'},
		 {name: '芬兰  Finland', value: '芬兰'},
		 {name: '瑞典  Sweden', value: '瑞典'},
		 {name: '挪威  Norway', value: '挪威'},
		 {name: '冰岛  Iceland', value: '冰岛'},
		 {name: '丹麦  Denmark', value: '丹麦'},
		 {name: '法罗群岛  Faroe islands', value: '法罗群岛'},
		 {name: '爱沙尼亚  Estonia', value: '爱沙尼亚'},
		 {name: '拉脱维亚  Latvia', value: '拉脱维亚'},
		 {name: '立陶宛  Lithuania', value: '立陶宛'},
		 {name: '白俄罗斯  The Republic of Belarus', value: '白俄罗斯'},
		 {name: '俄罗斯  Russia', value: '俄罗斯'},
		 {name: '乌克兰  Ukraine', value: '乌克兰'},
		 {name: '摩尔多瓦  Moldova', value: '摩尔多瓦'},
		 {name: '波兰  Poland', value: '波兰'},
		 {name: '捷克  Czechoslovakia', value: '捷克'},
		 {name: '斯洛伐克  The Slovak Republic', value: '斯洛伐克'},
		 {name: '匈牙利  Hungary', value: '匈牙利'},
		 {name: '德国  Germany', value: '德国'},
		 {name: '奥地利  Austria', value: '奥地利'},
		 {name: '瑞士  Switzerland', value: '瑞士'},
		 {name: '列支敦士登  Liechtenstein', value: '列支敦士登'},
		 {name: '英国  United Kingdom', value: '英国'},
		 {name: '爱尔兰  Ireland', value: '爱尔兰'},
		 {name: '荷兰  Netherlands', value: '荷兰'},
		 {name: '比利时  Belgium', value: '比利时'},
		 {name: '卢森堡  Luxembourg', value: '卢森堡'},
		 {name: '法国  France', value: '法国'},
		 {name: '摩纳哥  Monaco', value: '摩纳哥'},
		 {name: '罗马尼亚  Roumania', value: '罗马尼亚'},
		 {name: '保加利亚  Bulgaria', value: '保加利亚'},
		 {name: '塞尔维亚  Serbia', value: '塞尔维亚'},
		 {name: '马其顿  Macedonia', value: '马其顿'},
		 {name: '阿尔巴尼亚  Albania', value: '阿尔巴尼亚'},
		 {name: '希腊  Greece', value: '希腊'},
		 {name: '斯洛文尼亚  Slovenia', value: '斯洛文尼亚'},
		 {name: '克罗地亚  Croatia', value: '克罗地亚'},
		 {name: '波墨  Bosnia and ink plug elder brother d that', value: '波墨'},
		 {name: '意大利  Italy', value: '意大利'},
		 {name: '梵蒂冈  Vatican', value: '梵蒂冈'},
		 {name: '圣马力诺  San Marino', value: '圣马力诺'},
		 {name: '马耳他  Malta', value: '马耳他'},
		 {name: '西班牙  Spain', value: '西班牙'},
		 {name: '葡萄牙  Portugal', value: '葡萄牙'},
		 {name: '安道尔  Andorra', value: '安道尔'},
		 {name: '非洲  Africa', value: '非洲'},
		 {name: '埃及  Egypt', value: '埃及'},
		 {name: '利比亚  Libya', value: '利比亚'},
		 {name: '苏丹  Sultan', value: '苏丹'},
		 {name: '突尼斯  Tunisia', value: '突尼斯'},
		 {name: '阿尔及利亚  Algeria', value: '阿尔及利亚'},
		 {name: '摩洛哥  Morocco', value: '摩洛哥'},
		 {name: '亚速尔群岛  Azores', value: '亚速尔群岛'},
		 {name: '马德拉群岛  Madeira', value: '马德拉群岛'},
		 {name: '埃塞俄比亚  Ethiopia', value: '埃塞俄比亚'},
		 {name: '厄立特里亚  Eritrea', value: '厄立特里亚'},
		 {name: '索马里  Somalia', value: '索马里'},
		 {name: '吉布提  Djibouti', value: '吉布提'},
		 {name: '肯尼亚  Kenya', value: '肯尼亚'},
		 {name: '坦桑尼亚  Tanzania', value: '坦桑尼亚'},
		 {name: '乌干达  Uganda', value: '乌干达'},
		 {name: '卢旺达  Rwanda', value: '卢旺达'},
		 {name: '布隆迪  Burundi', value: '布隆迪'},
		 {name: '塞舌尔  Seychelles', value: '塞舌尔'},
		 {name: '乍得  Chad', value: '乍得'},
		 {name: '中非  Central Africa', value: '中非'},
		 {name: '喀麦隆  Cameroon', value: '喀麦隆'},
		 {name: '赤道几内亚  Equatorial Guinea', value: '赤道几内亚'},
		 {name: '加蓬  Gabon', value: '加蓬'},
		 {name: '刚果  Congo', value: '刚果'},
		 {name: '圣普  Sao Tome and Principe', value: '圣普'},
		 {name: '毛里塔尼亚  Mauritania', value: '毛里塔尼亚'},
		 {name: '西撒哈拉  EH West Sahara', value: '西撒哈拉'},
		 {name: '塞内加尔  Senegal', value: '塞内加尔'},
		 {name: '冈比亚  Gambia', value: '冈比亚'},
		 {name: '马里  Mali', value: '马里'},
		 {name: '布基纳法索  Burkina faso', value: '布基纳法索'},
		 {name: '几内亚  Guinea', value: '几内亚'},
		 {name: '几内亚比绍  Guinea-Bissau', value: '几内亚比绍  Guinea-'},
		 {name: '佛得角  Cape Verde', value: '佛得角'},
		 {name: '塞拉利昂  Sierra leone', value: '塞拉利昂'},
		 {name: '利比里亚  Liberia', value: '利比里亚'},
		 {name: "科特迪瓦  Cote d'ivoire", value: "科特迪瓦  Cote d'"},
		 {name: '加纳  Ghana', value: '加纳'},
		 {name: '多哥  Togo', value: '多哥'},
		 {name: '贝宁  Benin', value: '贝宁'},
		 {name: '尼日尔  The Niger', value: '尼日尔'},
		 {name: '加那利群岛  Canary Islands', value: '加那利群岛'},
		 {name: '赞比亚  Zambia', value: '赞比亚'},
		 {name: '安哥拉  Angola', value: '安哥拉'},
		 {name: '津巴布韦  Zimbabwe', value: '津巴布韦'},
		 {name: '马拉维  Malawi', value: '马拉维'},
		 {name: '莫桑比克  Mozambique', value: '莫桑比克'},
		 {name: '博茨瓦纳  Botswana', value: '博茨瓦纳'},
		 {name: '纳米比亚  Namibia', value: '纳米比亚'},
		 {name: '南非  South Africa', value: '南非'},
		 {name: '斯威士兰  Swaziland', value: '斯威士兰'},
		 {name: '莱索托  Lesotho', value: '莱索托'},
		 {name: '马达加斯加  Madagascar', value: '马达加斯加'},
		 {name: '科摩罗  Comorin', value: '科摩罗'},
		 {name: '毛里求斯  Mauritius', value: '毛里求斯'},
		 {name: '留尼旺  Reunion', value: '留尼旺'},
		 {name: '圣赫勒拿  Saint Helena', value: '圣赫勒拿'},
		 {name: '尼日利亚  Federal Republic of Nigeria', value: '尼日利亚'},
		 {name: '海外及港澳台  海外及港澳台', value: '海外及港澳台'}
];